from fastapi import APIRouter, Depends

from auth import get_current_user, require_platform_role
from config import get_settings
from database import Database, get_database
from services.saas_subscription_service import PHASE_LABEL

router = APIRouter(prefix="/api/platform", tags=["platform"])


@router.get("/health")
async def health() -> dict:
    settings = get_settings()
    return {
        "ok": True,
        "service": "AeroAssist AgencyOS API",
        "app_env": settings.app_env,
        "phase": PHASE_LABEL,
    }


@router.get("/summary")
async def summary(
    user: dict = Depends(require_platform_role(["platform_owner", "platform_admin", "platform_support"])),
    db: Database = Depends(get_database),
) -> dict:
    platform_owner_count = await db.collection("platform_users").count({"global_role": "platform_owner", "status": "active"})
    agency_count = await db.collection("agencies").count()
    workspace_count = await db.collection("agency_workspaces").count()
    staff_membership_count = await db.collection("agency_staff_memberships").count()
    staff_invitation_count = await db.collection("invitations").count({"invitation_type": "agency_staff"})
    branding_settings = await db.collection("agency_branding_settings").find_many()
    website_settings = await db.collection("agency_website_settings").find_many()
    request_intakes = await db.collection("request_intakes").find_many()
    open_operational_requests = [
        item
        for item in await db.collection("travel_requests").find_many()
        if item.get("status") not in {"closed", "cancelled", "archived"}
    ]
    return {
        "current_user": user,
        "counts": {
            "agencies": agency_count,
            "workspaces": workspace_count,
            "staff_memberships": staff_membership_count,
            "agency_branding_settings": len(branding_settings),
            "agency_branding_logos": len([item for item in branding_settings if item.get("logo_storage_record_id")]),
            "agency_branding_logo_assets": await db.collection("agency_branding_assets").count(),
            "agency_website_settings": len(website_settings),
            "active_agency_websites": len([item for item in website_settings if item.get("status") == "active"]),
            "agency_website_pages": await db.collection("agency_website_pages").count(),
            "agency_website_media_assets": await db.collection("agency_website_media_assets").count(),
            "public_agency_website_media_assets": await db.collection("agency_website_media_assets").count({"status": "active", "public_usage_allowed": True, "is_public_safe": True}),
            "trip_dossiers": await db.collection("trip_dossiers").count(),
            "request_case_flags": await db.collection("request_case_flags").count(),
            "website_origin_intakes": await db.collection("request_intakes").count({"source": "agency_website"}),
            "clients": await db.collection("client_profiles").count(),
            "passengers": await db.collection("passenger_profiles").count(),
            "relationships": await db.collection("client_passenger_relationships").count(),
            "request_intakes": len(request_intakes),
            "new_request_intakes": len([item for item in request_intakes if item.get("status") == "new"]),
            "converted_request_intakes": len([item for item in request_intakes if item.get("status") == "converted"]),
            "requests": await db.collection("travel_requests").count(),
            "open_operational_requests": len(open_operational_requests),
            "request_tasks": await db.collection("request_tasks").count(),
            "offers": await db.collection("offers").count(),
            "offer_routes": await db.collection("offer_route_alternatives").count(),
            "offer_fare_options": await db.collection("offer_fare_options").count(),
            "offer_workspaces": await db.collection("offer_workspaces").count(),
            "offer_options": await db.collection("offer_options").count(),
            "offer_builder_segments": await db.collection("offer_builder_segments").count(),
            "offer_fare_bundles": await db.collection("offer_fare_bundles").count(),
            "offer_pricing_lines": await db.collection("offer_pricing_lines").count(),
            "offer_comparison_snapshots": await db.collection("offer_comparison_snapshots").count(),
            "offer_acceptances": await db.collection("offer_acceptances").count(),
            "trip_accepted_offer_snapshots": await db.collection("trip_accepted_offer_snapshots").count(),
            "booking_readiness_packages": await db.collection("booking_readiness_packages").count(),
            "booking_workspaces": await db.collection("booking_workspaces").count(),
            "booking_records": await db.collection("booking_records").count(),
            "booking_import_drafts": await db.collection("booking_import_drafts").count(),
            "trip_change_operations": await db.collection("trip_change_operations").count(),
            "bookings": await db.collection("bookings").count(),
            "tickets": await db.collection("ticket_records").count(),
            "ticket_coupons": await db.collection("ticket_coupons").count(),
            "emds": await db.collection("emd_records").count(),
            "emd_coupons": await db.collection("emd_coupons").count(),
            "ticket_exchange_operations": await db.collection("ticket_exchange_operations").count(),
            "emd_exchange_operations": await db.collection("emd_exchange_operations").count(),
            "ticket_emd_timeline_events": await db.collection("ticket_emd_timeline_events").count(),
            "ancillary_pricing_rules": await db.collection("airline_ancillary_pricing_rules").count(),
            "ancillary_price_components": await db.collection("airline_ancillary_price_components").count(),
            "ancillary_pricing_applicability": await db.collection("airline_ancillary_pricing_applicability").count(),
            "ancillary_pricing_matrices": await db.collection("airline_ancillary_pricing_matrices").count(),
            "ancillary_pricing_matrix_rows": await db.collection("airline_ancillary_pricing_matrix_rows").count(),
            "airline_service_exception_rules": await db.collection("airline_service_exception_rules").count(),
            "price_quote_scenarios": await db.collection("airline_service_price_quote_scenarios").count(),
            "price_quote_results": await db.collection("airline_service_price_quote_results").count(),
            "candidate_pricing_links": await db.collection("policy_candidate_pricing_links").count(),
            "policy_comparison_profiles": await db.collection("airline_policy_comparison_profiles").count(),
            "policy_comparison_snapshots": await db.collection("airline_policy_comparison_snapshots").count(),
            "policy_comparison_rows": await db.collection("airline_policy_comparison_rows").count(),
            "service_advisor_scenarios": await db.collection("airline_service_advisor_scenarios").count(),
            "service_advisor_results": await db.collection("airline_service_advisor_results").count(),
            "policy_comparison_saved_views": await db.collection("airline_policy_comparison_saved_views").count(),
            "offer_policy_advisor_contexts": await db.collection("offer_policy_advisor_contexts").count(),
            "offer_policy_advisor_airline_rows": await db.collection("offer_policy_advisor_airline_rows").count(),
            "offer_policy_advisor_warnings": await db.collection("offer_policy_advisor_warnings").count(),
            "offer_policy_advisor_decision_notes": await db.collection("offer_policy_advisor_decision_notes").count(),
            "offer_policy_advisor_saved_snapshots": await db.collection("offer_policy_advisor_saved_snapshots").count(),
            "offer_decision_packs": await db.collection("offer_decision_packs").count(),
            "offer_decision_pack_options": await db.collection("offer_decision_pack_options").count(),
            "offer_decision_pack_evidence": await db.collection("offer_decision_pack_evidence").count(),
            "offer_decision_pack_warnings": await db.collection("offer_decision_pack_warnings").count(),
            "offer_decision_pack_review_notes": await db.collection("offer_decision_pack_review_notes").count(),
            "offer_decision_pack_snapshots": await db.collection("offer_decision_pack_snapshots").count(),
            "offer_decision_explanations": await db.collection("offer_decision_explanations").count(),
            "offer_decision_timeline_events": await db.collection("offer_decision_timeline_events").count(),
            "offer_decision_evidence_references": await db.collection("offer_decision_evidence_references").count(),
            "offer_decision_reasons": await db.collection("offer_decision_reasons").count(),
            "offer_decision_acknowledgements": await db.collection("offer_decision_acknowledgements").count(),
            "offer_decision_audit_snapshots": await db.collection("offer_decision_audit_snapshots").count(),
            "offer_decision_exports": await db.collection("offer_decision_exports").count(),
            "offer_decision_export_sections": await db.collection("offer_decision_export_sections").count(),
            "offer_decision_export_artifacts": await db.collection("offer_decision_export_artifacts").count(),
            "offer_decision_export_recipient_drafts": await db.collection("offer_decision_export_recipient_drafts").count(),
            "offer_decision_export_audit_events": await db.collection("offer_decision_export_audit_events").count(),
            "offer_decision_export_previews": await db.collection("offer_decision_export_previews").count(),
            "offer_decision_export_preview_sections": await db.collection("offer_decision_export_preview_sections").count(),
            "offer_decision_export_preview_blocks": await db.collection("offer_decision_export_preview_blocks").count(),
            "offer_decision_export_preview_validations": await db.collection("offer_decision_export_preview_validations").count(),
            "offer_decision_export_preview_snapshots": await db.collection("offer_decision_export_preview_snapshots").count(),
            "offer_decision_export_approvals": await db.collection("offer_decision_export_approvals").count(),
            "offer_decision_export_approval_checkpoints": await db.collection("offer_decision_export_approval_checkpoints").count(),
            "offer_decision_export_release_readiness": await db.collection("offer_decision_export_release_readiness").count(),
            "offer_decision_export_release_holds": await db.collection("offer_decision_export_release_holds").count(),
            "offer_decision_export_release_snapshots": await db.collection("offer_decision_export_release_snapshots").count(),
            "offer_decision_export_delivery_handoffs": await db.collection("offer_decision_export_delivery_handoffs").count(),
            "offer_decision_export_delivery_recipients": await db.collection("offer_decision_export_delivery_recipients").count(),
            "offer_decision_export_delivery_attachments": await db.collection("offer_decision_export_delivery_attachments").count(),
            "offer_decision_export_delivery_instructions": await db.collection("offer_decision_export_delivery_instructions").count(),
            "offer_decision_export_delivery_snapshots": await db.collection("offer_decision_export_delivery_snapshots").count(),
            "offer_decision_export_delivery_outcomes": await db.collection("offer_decision_export_delivery_outcomes").count(),
            "offer_decision_export_delivery_outcome_events": await db.collection("offer_decision_export_delivery_outcome_events").count(),
            "offer_decision_export_delivery_receipts": await db.collection("offer_decision_export_delivery_receipts").count(),
            "offer_decision_export_delivery_issues": await db.collection("offer_decision_export_delivery_issues").count(),
            "offer_decision_export_delivery_outcome_snapshots": await db.collection("offer_decision_export_delivery_outcome_snapshots").count(),
            "offer_decision_export_audit_reviews": await db.collection("offer_decision_export_audit_reviews").count(),
            "offer_decision_export_audit_review_findings": await db.collection("offer_decision_export_audit_review_findings").count(),
            "offer_decision_export_audit_review_checklist_items": await db.collection("offer_decision_export_audit_review_checklist_items").count(),
            "offer_decision_export_audit_review_snapshots": await db.collection("offer_decision_export_audit_review_snapshots").count(),
            "offer_decision_export_governance_records": await db.collection("offer_decision_export_governance_records").count(),
            "offer_decision_export_governance_rules": await db.collection("offer_decision_export_governance_rules").count(),
            "offer_decision_export_retention_policies": await db.collection("offer_decision_export_retention_policies").count(),
            "offer_decision_export_legal_bases": await db.collection("offer_decision_export_legal_bases").count(),
            "offer_decision_export_archive_statuses": await db.collection("offer_decision_export_archive_statuses").count(),
            "offer_decision_export_governance_exceptions": await db.collection("offer_decision_export_governance_exceptions").count(),
            "offer_decision_export_governance_snapshots": await db.collection("offer_decision_export_governance_snapshots").count(),
            "offer_decision_export_compliance_evidence": await db.collection("offer_decision_export_compliance_evidence").count(),
            "offer_decision_export_compliance_requirements": await db.collection("offer_decision_export_compliance_requirements").count(),
            "offer_decision_export_compliance_checks": await db.collection("offer_decision_export_compliance_checks").count(),
            "offer_decision_export_compliance_results": await db.collection("offer_decision_export_compliance_results").count(),
            "offer_decision_export_compliance_exceptions": await db.collection("offer_decision_export_compliance_exceptions").count(),
            "offer_decision_export_compliance_snapshots": await db.collection("offer_decision_export_compliance_snapshots").count(),
            "airline_intelligence_data_packs": await db.collection("airline_intelligence_data_packs").count(),
            "airline_intelligence_data_pack_items": await db.collection("airline_intelligence_data_pack_items").count(),
            "airline_intelligence_data_pack_validation_issues": await db.collection("airline_intelligence_data_pack_validation_issues").count(),
            "airline_intelligence_data_pack_import_runs": await db.collection("airline_intelligence_data_pack_import_runs").count(),
            "airline_intelligence_data_pack_review_notes": await db.collection("airline_intelligence_data_pack_review_notes").count(),
            "airline_intelligence_coverage_snapshots": await db.collection("airline_intelligence_coverage_snapshots").count(),
            "airline_intelligence_data_pack_reviews": await db.collection("airline_intelligence_data_pack_reviews").count(),
            "airline_intelligence_data_pack_review_checklist_items": await db.collection("airline_intelligence_data_pack_review_checklist_items").count(),
            "airline_intelligence_data_pack_field_mappings": await db.collection("airline_intelligence_data_pack_field_mappings").count(),
            "airline_intelligence_data_pack_conflicts": await db.collection("airline_intelligence_data_pack_conflicts").count(),
            "airline_intelligence_data_pack_promotion_readiness": await db.collection("airline_intelligence_data_pack_promotion_readiness").count(),
            "airline_intelligence_data_pack_review_snapshots": await db.collection("airline_intelligence_data_pack_review_snapshots").count(),
            "airline_intelligence_knowledge_versions": await db.collection("airline_intelligence_knowledge_versions").count(),
            "airline_intelligence_knowledge_version_items": await db.collection("airline_intelligence_knowledge_version_items").count(),
            "airline_intelligence_knowledge_release_channels": await db.collection("airline_intelligence_knowledge_release_channels").count(),
            "airline_intelligence_knowledge_release_assignments": await db.collection("airline_intelligence_knowledge_release_assignments").count(),
            "airline_intelligence_knowledge_version_comparisons": await db.collection("airline_intelligence_knowledge_version_comparisons").count(),
            "airline_intelligence_knowledge_rollback_plans": await db.collection("airline_intelligence_knowledge_rollback_plans").count(),
            "airline_intelligence_knowledge_version_snapshots": await db.collection("airline_intelligence_knowledge_version_snapshots").count(),
            "airline_intelligence_agency_consumption_profiles": await db.collection("airline_intelligence_agency_consumption_profiles").count(),
            "airline_intelligence_agency_knowledge_assignment_views": await db.collection("airline_intelligence_agency_knowledge_assignment_views").count(),
            "airline_intelligence_agency_usage_readiness": await db.collection("airline_intelligence_agency_usage_readiness").count(),
            "airline_intelligence_agency_consumption_notes": await db.collection("airline_intelligence_agency_consumption_notes").count(),
            "airline_intelligence_agency_consumption_snapshots": await db.collection("airline_intelligence_agency_consumption_snapshots").count(),
            "saas_subscription_plans": await db.collection("saas_subscription_plans").count(),
            "saas_plan_entitlements": await db.collection("saas_plan_entitlements").count(),
            "agency_subscription_assignments": await db.collection("agency_subscription_assignments").count(),
            "agency_entitlement_readiness": await db.collection("agency_entitlement_readiness").count(),
            "agency_subscription_review_notes": await db.collection("agency_subscription_review_notes").count(),
            "agency_subscription_snapshots": await db.collection("agency_subscription_snapshots").count(),
            "agency_feature_flags": await db.collection("agency_feature_flags").count(),
            "agency_feature_flag_reviews": await db.collection("agency_feature_flag_reviews").count(),
            "agency_feature_flag_snapshots": await db.collection("agency_feature_flag_snapshots").count(),
            "agency_feature_flag_audits": await db.collection("agency_feature_flag_audits").count(),
            "agency_feature_flag_readiness": await db.collection("agency_feature_flag_readiness").count(),
            "agency_feature_flag_bundles": await db.collection("agency_feature_flag_bundles").count(),
            "agency_feature_flag_bundle_reviews": await db.collection("agency_feature_flag_bundle_reviews").count(),
            "agency_feature_bundle_assignments": await db.collection("agency_feature_bundle_assignments").count(),
            "agency_feature_bundle_assignment_history": await db.collection("agency_feature_bundle_assignment_history").count(),
            "agency_feature_bundle_rollout_readiness": await db.collection("agency_feature_bundle_rollout_readiness").count(),
            "agency_feature_bundle_rollout_plans": await db.collection("agency_feature_bundle_rollout_plans").count(),
            "feature_bundle_rollout_approvals": await db.collection("feature_bundle_rollout_approvals").count(),
            "feature_bundle_rollout_approval_notes": await db.collection("feature_bundle_rollout_approval_notes").count(),
            "feature_bundle_rollout_schedules": await db.collection("feature_bundle_rollout_schedules").count(),
            "feature_bundle_rollout_timeline_entries": await db.collection("feature_bundle_rollout_timeline_entries").count(),
            "feature_bundle_dependencies": await db.collection("feature_bundle_dependencies").count(),
            "feature_bundle_rollout_risks": await db.collection("feature_bundle_rollout_risks").count(),
            "feature_bundle_rollout_issues": await db.collection("feature_bundle_rollout_issues").count(),
            "feature_bundle_rollout_decisions": await db.collection("feature_bundle_rollout_decisions").count(),
            "feature_bundle_rollout_change_requests": await db.collection("feature_bundle_rollout_change_requests").count(),
            "feature_bundle_rollout_rollback_plans": await db.collection("feature_bundle_rollout_rollback_plans").count(),
            "feature_bundle_rollout_summary_packs": await db.collection("feature_bundle_rollout_summary_packs").count(),
            "operational_travel_workspaces": await db.collection("operational_travel_workspaces").count(),
            "travel_request_workspaces": await db.collection("travel_request_workspaces").count(),
            "passenger_workspaces": await db.collection("passenger_workspaces").count(),
            "flight_workspaces": await db.collection("flight_workspaces").count(),
            "trip_workspaces": await db.collection("trip_workspaces").count(),
            "rollout_dashboard_views": await db.collection("rollout_dashboard_views").count(),
            "rollout_dashboard_snapshots": await db.collection("rollout_dashboard_snapshots").count(),
            "capability_catalog": await db.collection("capability_catalog").count(),
            "ai_trace_events": await db.collection("ai_trace_events").count(),
            "adm_risk_events": await db.collection("adm_risk_events").count(),
            "gds_parse_samples": await db.collection("gds_parse_samples").count(),
            "gds_parser_profiles": await db.collection("gds_parser_profiles").count(),
            "gds_parser_versions": await db.collection("gds_parser_versions").count(),
            "gds_parser_runs": await db.collection("gds_parser_runs").count(),
            "gds_parsed_entities": await db.collection("gds_parsed_entities").count(),
            "gds_parse_corrections": await db.collection("gds_parse_corrections").count(),
            "gds_parse_training_samples": await db.collection("gds_parse_training_samples").count(),
            "gds_parser_evaluation_runs": await db.collection("gds_parser_evaluation_runs").count(),
            "airline_brand_assets": await db.collection("airline_brand_assets").count(),
            "invoices": await db.collection("invoices").count(),
            "payments": await db.collection("payment_records").count(),
            "portal_mappings": await db.collection("portal_access_mappings").count(),
            "airlines": await db.collection("airline_profiles").count(),
            "airline_knowledge": await db.collection("airline_knowledge_items").count(),
            "airline_procedures": await db.collection("airline_procedures").count(),
            "airline_emd_notes": await db.collection("airline_emd_rule_notes").count(),
            "airline_overrides": await db.collection("agency_airline_overrides").count(),
            "airline_rules_core": await db.collection("airline_rules_core").count(),
            "unified_exception_rules": await db.collection("unified_exception_rules").count(),
            "passenger_service_requests": await db.collection("passenger_service_requests").count(),
            "document_templates": await db.collection("document_templates").count(),
            "document_render_jobs": await db.collection("document_render_jobs").count(),
            "document_packages": await db.collection("document_packages").count(),
            "document_share_records": await db.collection("document_share_records").count(),
            "rendered_documents": await db.collection("rendered_documents").count(),
            "document_exports": await db.collection("document_exports").count(),
            "document_deliveries": await db.collection("document_deliveries").count(),
            "document_delivery_attempts": await db.collection("document_delivery_attempts").count(),
            "reference_records": await db.collection("global_reference_records").count(),
            "country_reference_records": await db.collection("global_reference_records").count({"domain": "countries"}),
            "airport_reference_records": await db.collection("global_reference_records").count({"domain": "airports"}),
            "airline_reference_records": await db.collection("global_reference_records").count({"domain": "airlines"}),
            "currency_reference_records": await db.collection("global_reference_records").count({"domain": "currencies"}),
            "language_reference_records": await db.collection("global_reference_records").count({"domain": "languages"}),
            "reference_domain_metadata": await db.collection("reference_domain_metadata").count(),
            "reference_suggestions": await db.collection("reference_data_suggestions").count(),
            "pending_reference_suggestions": await db.collection("reference_data_suggestions").count({"status": "pending_review"}),
            "reference_import_batches": await db.collection("reference_import_batches").count(),
            "service_catalogue_records": await db.collection("service_catalogue").count(),
            "global_field_definitions": await db.collection("global_field_definitions").count(),
            "agency_form_profiles": await db.collection("agency_form_profiles").count(),
            "agency_form_field_settings": await db.collection("agency_form_field_settings").count(),
            "request_passenger_segment_services": await db.collection("request_passenger_segment_services").count(),
            "request_pets": await db.collection("request_pets").count(),
            "request_pet_segment_transport": await db.collection("request_pet_segment_transport").count(),
            "request_special_items": await db.collection("request_special_items").count(),
            "request_special_item_segments": await db.collection("request_special_item_segments").count(),
            "canonical_service_domains": await db.collection("canonical_service_domains").count(),
            "canonical_service_families": await db.collection("canonical_service_families").count(),
            "canonical_service_variants": await db.collection("canonical_service_variants").count(),
            "airline_service_aliases": await db.collection("airline_service_aliases").count(),
            "service_taxonomy_mapping_rules": await db.collection("service_taxonomy_mapping_rules").count(),
            "policy_candidate_taxonomy_links": await db.collection("policy_candidate_taxonomy_links").count(),
            "airline_service_communication_rules": await db.collection("airline_service_communication_rules").count(),
            "ssr_osi_templates": await db.collection("ssr_osi_templates").count(),
            "ssr_osi_requirements": await db.collection("ssr_osi_requirements").count(),
            "ssr_status_recognition_rules": await db.collection("ssr_status_recognition_rules").count(),
            "airline_rejection_patterns": await db.collection("airline_rejection_patterns").count(),
            "airline_service_payment_rules": await db.collection("airline_service_payment_rules").count(),
            "airline_emd_issuance_rules": await db.collection("airline_emd_issuance_rules").count(),
            "airline_rfic_rfisc_mappings": await db.collection("airline_rfic_rfisc_mappings").count(),
            "airline_emd_interline_rules": await db.collection("airline_emd_interline_rules").count(),
            "airline_emd_lifecycle_rules": await db.collection("airline_emd_lifecycle_rules").count(),
            "policy_candidate_mechanics_links": await db.collection("policy_candidate_mechanics_links").count(),
            "audit_events": await db.collection("audit_events").count(),
        },
        "production_onboarding": {
            "platform_owner_exists": platform_owner_count > 0,
            "agency_exists": agency_count > 0,
            "workspace_exists": workspace_count > 0,
            "staff_membership_or_invitation_exists": staff_membership_count > 0 or staff_invitation_count > 0,
            "staff_invitations": staff_invitation_count,
        },
        "implemented_layers": [
            "AeroAssist Global / Platform Owner",
            "Agency Workspace foundation",
            "CRM client/passenger relationship foundation",
            "Request intake, messages, tasks, and timeline foundation",
            "Manual offer builder foundation",
            "Booking, ticket, EMD, invoice, and payment tracking foundation",
            "Airline Intelligence foundation",
            "Branded HTML document output foundation",
            "Read-only client portal visibility foundation",
            "Persistence and tenant hardening foundation",
            "Authentication and invitation foundation",
            "Controlled client portal actions foundation",
            "Refund and exchange tracking foundation",
            "Printable document export and manual delivery foundation",
            "Document delivery hardening foundation",
            "Production PDF rendering and delivery infrastructure foundation",
            "Production delivery operations and secret resolution foundation",
            "Production configuration hardening foundation",
            "Docker and Hostinger VPS packaging foundation",
            "VPS reverse proxy, TLS, backup, and operations runbook foundation",
            "Hostinger VPS first deployment preparation foundation",
            "Production bootstrap and go-live hardening foundation",
            "Production onboarding and agency setup foundation",
            "Backup automation and lightweight monitoring readiness foundation",
            "Staff invitation acceptance and team access hardening foundation",
            "Document storage lifecycle and delivery provider readiness foundation",
            "Request intake triage and operational request conversion foundation",
            "Operational request builder V1 foundation",
            "Mobility assistance logic and request builder UX correction",
            "Assistance assessment driven SSR recommendation",
            "Agency branding, theme, and UI personalization foundation",
            "AgencyOS app shell, sidebar navigation, and visual polish stabilization",
            "Agency website builder and CMS foundation",
            "Public website publishing, intake forms, and CMS content blocks",
            "Branding, logo asset management, and agency settings stabilization",
            "CMS media library, website image assets, and public website visual polish",
            "Blueprint alignment and canonical operations model foundation",
            "Reference data core and service catalogue foundation",
            "Global reference governance, suggestion queue, and bulk import foundation",
            "Segment-scoped request services, pets, and special items foundation",
            "Global field library and agency form profile foundation",
            "Platform reference data console and enriched country metadata foundation",
            "Reference enrichment import packs and aviation normalization foundation",
            "Offer acceptance, trip accepted-offer snapshots, and booking readiness foundation",
            "Booking workspace and manual PNR mirror foundation",
            "Ticket and EMD mirror foundation",
            "Supplementary blueprint adoption and canonical route sync foundation",
            "Standalone booking, import draft, and existing-trip change/exchange mirror foundation",
            "Document foundation for templates, render jobs, packages, and internal share records",
            "GDS parser profiles, versions, runs, entities, corrections, training samples, and evaluations foundation",
            "Airline policy ingestion source, extraction, review, and approved knowledge foundation",
            "Canonical service taxonomy foundation",
            "SSR/OSI and EMD/RFIC/RFISC service mechanics mapping foundation",
            "Ancillary pricing schema and exception engine expansion foundation",
            "Airline policy comparison and service advisor foundation",
            "Offer builder policy advisor integration foundation",
            "Offer builder advisor consumption and decision pack foundation",
        ],
        "not_yet_implemented": [
            "Document upload workflows",
            "Payment gateway integration",
            "Public document links",
            "Automatic document sending or provider webhooks",
            "Automatic booking, ticketing, or airline execution from portal actions",
            "Live SSR/OSI/GDS/NDC/provider exchange, refund, void, or reissue execution",
            "External AI parser execution",
            "Full GDS host grammar coverage and provider reconciliation",
            "Invoice, payment, accounting, BSP/ARC, and settlement execution from ancillary estimates",
            "Automatic airline recommendation or provider execution from service advisor metadata",
            "Automatic offer airline selection, offer price mutation, booking, ticketing, EMD issuance, payment, invoice, settlement, or provider execution from offer policy advisor metadata",
            "Automatic winner ranking, offer price mutation, booking, ticketing, EMD issuance, payment, invoice, settlement, or provider execution from offer decision packs",
        ],
    }


@router.get("/audit-events")
async def audit_events(
    user: dict = Depends(require_platform_role(["platform_owner", "platform_admin", "platform_support"])),
    db: Database = Depends(get_database),
) -> dict:
    return {"items": await db.collection("audit_events").find_many()}


@router.get("/whoami")
async def whoami(user: dict = Depends(get_current_user)) -> dict:
    return {"user": user}
