from __future__ import annotations

from typing import Any


PHASE_LABEL = "phase_41_4_trip_workspace_foundation"


ADOPTION_ITEMS: list[dict[str, Any]] = [
    {
        "category": "RBAC",
        "concept": "Authentication & RBAC",
        "supplementary_concept": "users, roles, user_roles, permissions, role_permissions",
        "current_equivalent": "platform_users, auth_identities, auth_sessions, agency_staff_memberships, invitation records, platform/agency role helpers",
        "status": "built differently",
        "action": "Do not duplicate RBAC; current platform and agency role model remains canonical.",
    },
    {
        "category": "Airline Intelligence",
        "concept": "Airlines and operating intelligence",
        "supplementary_concept": "airlines, airline_contacts, airline_fleet, aircraft, routes, fare families, RBD matrix, fare rules, ancillaries, interline, distribution, PSS/GDS parameters, exception rules",
        "current_equivalent": "airline_profiles, airline_intelligence_profiles, airline_contacts, airline_fleet_types, aircraft_tail_numbers, aircraft_configurations, aircraft_seatmaps, airline_routes, airline_fare_families, airline_rbd_matrix_rows, airline_fare_rules, airline_ancillaries, airline_interline_agreements, airline_distribution_profiles, airline_pss_parameters, airline_gds_parameters, unified_exception_rules, airline_intelligence_data_packs with staged pack items, validation issues, import runs, review notes, and coverage snapshots, plus data pack review, promotion-readiness, knowledge versioning, publication-control metadata, and agency consumption bridge metadata",
        "status": "foundation adopted",
        "action": "Use Phase 39.0 data packs, Phase 39.1 review records, Phase 39.2 knowledge versions, and Phase 39.3 agency consumption bridge records as metadata-only staging, review, publication-control, and safe-use evidence before any future explicit promotion into operational airline tables.",
    },
    {
        "category": "Airline Intelligence Data Packs",
        "concept": "Governed airline data pack staging",
        "supplementary_concept": "airline data pack, seeded coverage pack, staged import, coverage readiness, CRM/CMS/client portal display flags",
        "current_equivalent": "airline_intelligence_data_packs, airline_intelligence_data_pack_items, airline_intelligence_data_pack_validation_issues, airline_intelligence_data_pack_import_runs, airline_intelligence_data_pack_review_notes, airline_intelligence_coverage_snapshots",
        "status": "foundation adopted",
        "action": "Stage and validate airline intelligence metadata for future CRM, CMS, client portal, offer builder, and special-services use without scraping, external APIs, external AI, automatic promotion, recommendations, provider/GDS execution, booking, PNR mutation, ticketing, EMD issuance, payments, invoices, settlement, public publishing, or automatic sending.",
    },
    {
        "category": "Airline Intelligence Data Pack Reviews",
        "concept": "Data pack review and promotion-readiness metadata",
        "supplementary_concept": "review checklist, field mapping, duplicate/conflict detection, promotion readiness, safe consumption flags",
        "current_equivalent": "airline_intelligence_data_pack_reviews, airline_intelligence_data_pack_review_checklist_items, airline_intelligence_data_pack_field_mappings, airline_intelligence_data_pack_conflicts, airline_intelligence_data_pack_promotion_readiness, airline_intelligence_data_pack_review_snapshots",
        "status": "foundation adopted",
        "action": "Review staged airline data packs with checklist, mapping, conflict, readiness, and agency-readable coverage metadata without automatic promotion, scraping, external APIs, external AI, publishing, recommendations, provider execution, booking, PNR mutation, ticketing, EMD issuance, payments, invoices, or settlement.",
    },
    {
        "category": "Airline Intelligence Knowledge Versions",
        "concept": "Knowledge versioning and publication-control metadata",
        "supplementary_concept": "knowledge versions, release channels, assignments, comparisons, rollback plans, immutable version snapshots",
        "current_equivalent": "airline_intelligence_knowledge_versions, airline_intelligence_knowledge_version_items, airline_intelligence_knowledge_release_channels, airline_intelligence_knowledge_release_assignments, airline_intelligence_knowledge_version_comparisons, airline_intelligence_knowledge_rollback_plans, airline_intelligence_knowledge_version_snapshots",
        "status": "foundation adopted",
        "action": "Group reviewed airline intelligence into governed metadata-only knowledge versions with release-channel visibility, comparison, rollback planning, and agency read-only version summaries without operational promotion or public publishing.",
    },
    {
        "category": "Airline Intelligence Agency Consumption",
        "concept": "Agency safe-use consumption bridge",
        "supplementary_concept": "agency consumption profiles, assignment views, usage readiness, notes, immutable consumption snapshots",
        "current_equivalent": "airline_intelligence_agency_consumption_profiles, airline_intelligence_agency_knowledge_assignment_views, airline_intelligence_agency_usage_readiness, airline_intelligence_agency_consumption_notes, airline_intelligence_agency_consumption_snapshots",
        "status": "foundation adopted",
        "action": "Expose platform-governed airline intelligence knowledge versions to agency CRM, CMS, client portal, and offer builder work areas through read-only metadata and plain-language safe-use summaries without publishing, recommendations, provider execution, booking, PNR mutation, ticketing, EMD issuance, payments, invoices, settlement, scraping, external APIs, or external AI.",
    },
    {
        "category": "Platform / Agency UX",
        "concept": "Platform Console and Agency Workspace navigation clarity",
        "supplementary_concept": "owner console groups, agency workspace groups, plain-language labels, helper badges, metadata-only UX boundaries",
        "current_equivalent": "frontend module catalog, PlatformLayout, AgencyLayout, platform dashboard, agency dashboard, and platform_agency_ux_consolidation readiness metadata",
        "status": "foundation adopted",
        "action": "Clarify platform-owner and agency-staff mental models through grouped metadata-only navigation without new route roots, publishing, recommendations, provider execution, booking, PNR mutation, ticketing, EMD issuance, payments, invoices, settlement, scraping, external APIs, or external AI.",
    },
    {
        "category": "SaaS Subscriptions",
        "concept": "Subscription plans and agency entitlements",
        "supplementary_concept": "plans, module entitlements, data-pack entitlements, agency subscription assignments, entitlement readiness, review notes, immutable snapshots",
        "current_equivalent": "saas_subscription_plans, saas_plan_entitlements, agency_subscription_assignments, agency_entitlement_readiness, agency_subscription_review_notes, agency_subscription_snapshots",
        "status": "foundation adopted",
        "action": "Define metadata-only SaaS subscription and entitlement visibility without billing, payment, invoicing, settlement, automatic access enforcement, publishing, recommendations, provider execution, booking, PNR mutation, ticketing, EMD issuance, scraping, external APIs, or external AI.",
    },
    {
        "category": "Subscription Entitlement UI Guardrails",
        "concept": "Read-only subscription visibility hints",
        "supplementary_concept": "module visibility badges, entitlement review summaries, agency navigation status hints",
        "current_equivalent": "SaaSSubscriptionService agency_module_visibility/platform_entitlement_visibility helpers, /api/platform/saas-subscriptions/entitlement-visibility, /api/agencies/{agency_id}/saas-subscriptions/module-visibility, frontend module catalog entitlement keys",
        "status": "foundation adopted",
        "action": "Show Included, Limited, Review required, Not included, and Unknown as informational UI hints only; do not bill, charge, invoice, settle, block routes destructively, enforce access automatically, execute providers, book, mutate PNRs, ticket, issue EMDs, scrape, call external APIs, call external AI, or send automatically.",
    },
    {
        "category": "Agency Feature Flags",
        "concept": "Agency-specific feature visibility metadata",
        "supplementary_concept": "feature flags, agency feature visibility, feature review notes, immutable feature snapshots",
        "current_equivalent": "AgencyFeatureFlag, AgencyFeatureFlagReview, AgencyFeatureFlagSnapshot, /api/platform/feature-flags, /api/agencies/{agency_id}/feature-flags, /platform/feature-flags, /agency/feature-availability",
        "status": "foundation adopted",
        "action": "Record agency-specific feature availability states for Platform Console review and Agency Workspace read-only visibility without billing, payments, automatic entitlement enforcement, feature blocking, provider execution, booking, PNR mutation, ticketing, EMD issuance, publishing, scraping, external APIs, external AI, or automatic sending.",
    },
    {
        "category": "Agency Feature Flag Audit",
        "concept": "Feature flag readiness and audit history metadata",
        "supplementary_concept": "feature audit trail, feature readiness checklist, rollout review metadata",
        "current_equivalent": "AgencyFeatureFlagAudit, AgencyFeatureFlagReadiness, /api/platform/feature-flags/audits, /api/platform/feature-flags/readiness, /api/agencies/{agency_id}/feature-readiness, /platform/feature-flag-audit, /agency/feature-readiness",
        "status": "foundation adopted",
        "action": "Record read-only feature flag audit history and readiness checklist metadata without feature enforcement, route blocking, permission changes, subscription changes, billing, provider execution, publishing, external APIs, external AI, scraping, or automatic sending.",
    },
    {
        "category": "Feature Flag Bundles",
        "concept": "Reusable feature flag bundle metadata",
        "supplementary_concept": "Core Agency, CRM, Ticketing, Booking, Airline Intelligence, GDS, Finance, Premium Operations, Beta Features, Internal Testing",
        "current_equivalent": "FeatureFlagBundle, FeatureFlagBundleSummary, FeatureFlagBundleReview, FeatureFlagBundleMember, BundleReadiness, /api/platform/feature-flag-bundles, /api/agencies/{agency_id}/feature-flag-bundles, /platform/feature-flag-bundles, /agency/feature-bundles",
        "status": "foundation adopted",
        "action": "Define reusable metadata-only groupings of feature flags for Platform Console review and Agency Workspace read-only visibility without enabling features, entitlement checks, route blocking, module hiding, permission decisions, billing, publishing, rollout, background workers, notifications, provider integrations, scraping, external APIs, or external AI.",
    },
    {
        "category": "Feature Bundle Assignments",
        "concept": "Agency feature bundle assignment metadata",
        "supplementary_concept": "agency bundle assignment records, assignment history, inactive assignment metadata",
        "current_equivalent": "AgencyFeatureBundleAssignment, AgencyFeatureBundleAssignmentHistory, AgencyFeatureBundleAssignmentService, /api/platform/feature-bundle-assignments, /api/platform/agencies/{agency_id}/bundle-assignments, /api/agencies/{agency_id}/feature-bundle-assignments, /platform/feature-bundle-assignments, /agency/assigned-bundles",
        "status": "foundation adopted",
        "action": "Record platform-owned agency bundle assignment metadata and immutable assignment history without activating features, evaluating entitlements, changing permissions, billing, licensing, executing feature flags, calling providers, running background workers or cron, calling external AI, or deploying anything.",
    },
    {
        "category": "Feature Bundle Dependencies",
        "concept": "Feature bundle dependency metadata",
        "supplementary_concept": "bundle dependencies, capability dependencies, approval dependencies, plan dependencies, schedule dependencies, readiness checklist dependencies",
        "current_equivalent": "FeatureBundleDependency, FeatureBundleDependencyReference, FeatureBundleDependencyType, FeatureBundleDependencyService, /api/platform/feature-bundle-dependencies, /api/agencies/{agency_id}/feature-bundle-dependencies, /platform/feature-bundle-dependencies, /agency/bundle-dependencies",
        "status": "foundation adopted",
        "action": "Record informational dependency metadata from bundles to bundles, capabilities, approvals, rollout plans, schedules, and readiness checklists without executing rollouts, scheduling background jobs, enforcing dependencies, blocking rollouts, activating bundles, modifying permissions, sending notifications, publishing, calling providers, or automating actions.",
    },
    {
        "category": "Feature Bundle Rollout Risk Register",
        "concept": "Feature bundle rollout risk register metadata",
        "supplementary_concept": "rollout risks, missing approval, dependency readiness, agency impact, schedule conflicts, documentation gaps, operational concerns",
        "current_equivalent": "FeatureBundleRolloutRisk, FeatureBundleRolloutRiskImpact, FeatureBundleRolloutRiskLikelihood, FeatureBundleRolloutRiskStatus, FeatureBundleRolloutRiskService, /api/platform/feature-bundle-rollout-risks, /api/agencies/{agency_id}/feature-bundle-rollout-risks, /platform/feature-bundle-rollout-risks, /agency/rollout-risks",
        "status": "foundation adopted",
        "action": "Record informational rollout risk metadata with impact, likelihood, status, mitigation, owner, and review notes without executing rollouts, enforcing risk decisions, blocking anything, sending notifications, activating bundles, automating actions, or calling external providers.",
    },
    {
        "category": "Feature Bundle Rollout Issue Log",
        "concept": "Feature bundle rollout issue log metadata",
        "supplementary_concept": "rollout issues, failed checklist item, approval follow-up, unresolved dependency, unclear rollout date, agency confusion, documentation gap, internal review concern",
        "current_equivalent": "FeatureBundleRolloutIssue, FeatureBundleRolloutIssueSeverity, FeatureBundleRolloutIssueStatus, FeatureBundleRolloutIssueService, /api/platform/feature-bundle-rollout-issues, /api/agencies/{agency_id}/feature-bundle-rollout-issues, /platform/feature-bundle-rollout-issues, /agency/rollout-issues",
        "status": "foundation adopted",
        "action": "Record informational rollout issue metadata with severity, status, owner, resolution notes, and review notes without executing rollouts, activating bundles, enforcing blocking, sending notifications, calling external providers, adding AI/provider execution, or automating actions.",
    },
    {
        "category": "Feature Bundle Rollout Decision Register",
        "concept": "Feature bundle rollout decision register metadata",
        "supplementary_concept": "rollout decisions, review decisions, rollout reasons, decision owners, related bundle/risk/issue/dependency/timeline references",
        "current_equivalent": "FeatureBundleRolloutDecision, FeatureBundleRolloutDecisionCategory, FeatureBundleRolloutDecisionStatus, FeatureBundleRolloutDecisionService, /api/platform/feature-bundle-rollout-decisions, /api/agencies/{agency_id}/feature-bundle-rollout-decisions, /platform/feature-bundle-rollout-decisions, /agency/rollout-decisions",
        "status": "foundation adopted",
        "action": "Record informational rollout decision metadata with reasons, owners, categories, statuses, and related rollout references without executing rollouts, automating deployments, activating features, enforcing entitlements, billing, calling providers or external APIs, using AI, notifying users, publishing, switching runtime behavior, or automating actions.",
    },
    {
        "category": "Feature Bundle Rollout Change Requests",
        "concept": "Feature bundle rollout change request metadata",
        "supplementary_concept": "rollout change requests, requested rollout changes, affected bundles, affected feature flags, related decisions, risks, issues, and dependencies",
        "current_equivalent": "FeatureBundleRolloutChangeRequest, FeatureBundleRolloutChangeRequestType, FeatureBundleRolloutChangeRequestPriority, FeatureBundleRolloutChangeRequestImpactLevel, FeatureBundleRolloutChangeRequestStatus, FeatureBundleRolloutChangeRequestService, /api/platform/feature-bundle-rollout-change-requests, /api/agencies/{agency_id}/feature-bundle-rollout-change-requests, /platform/feature-bundle-rollout-change-requests, /agency/rollout-change-requests",
        "status": "foundation adopted",
        "action": "Record informational rollout change request metadata with reasons, requesters, priorities, impact levels, statuses, affected records, and related rollout references without executing rollouts, automating deployments, activating features, enforcing entitlements, billing, calling providers or external APIs, using AI, notifying users, publishing, switching runtime behavior, or automating actions.",
    },
    {
        "category": "Feature Bundle Rollout Rollback Plans",
        "concept": "Feature bundle rollout rollback plan metadata",
        "supplementary_concept": "rollout rollback plans, rollback triggers, rollback scopes, affected bundles, affected feature flags, related change requests, decisions, risks, issues, and dependencies",
        "current_equivalent": "FeatureBundleRolloutRollbackPlan, FeatureBundleRolloutRollbackTrigger, FeatureBundleRolloutRollbackScope, FeatureBundleRolloutRollbackStatus, FeatureBundleRolloutRollbackPriority, FeatureBundleRolloutRollbackPlanService, /api/platform/feature-bundle-rollout-rollback-plans, /api/agencies/{agency_id}/feature-bundle-rollout-rollback-plans, /platform/feature-bundle-rollout-rollback-plans, /agency/rollout-rollback-plans",
        "status": "foundation adopted",
        "action": "Record informational rollback plan metadata with triggers, scopes, priorities, statuses, affected records, related rollout references, rollback steps, and validation notes without executing rollbacks, automating deployments, activating or deactivating features, enforcing entitlements, billing, calling providers or external APIs, using AI, notifying users, publishing, switching runtime behavior, or automating actions.",
    },
    {
        "category": "Feature Bundle Rollout Summary Packs",
        "concept": "Feature bundle rollout summary evidence-pack metadata",
        "supplementary_concept": "rollout summary packs, evidence packs, readiness references, approval references, schedule references, timeline references, dependency references, risk references, issue references, decision references, change request references, rollback plan references",
        "current_equivalent": "FeatureBundleRolloutSummaryPack, FeatureBundleRolloutSummaryPackStatus, FeatureBundleRolloutSummaryPackAudience, FeatureBundleRolloutSummaryPackService, /api/platform/feature-bundle-rollout-summary-packs, /api/agencies/{agency_id}/feature-bundle-rollout-summary-packs, /platform/feature-bundle-rollout-summary-packs, /agency/rollout-summary-packs",
        "status": "foundation adopted",
        "action": "Record informational rollout summary evidence-pack metadata with covered bundles, rollout references, evidence notes, and compliance notes without executing rollouts, automating deployments, activating or deactivating features, enforcing entitlements, billing, calling providers or external APIs, using AI, notifying users, publishing, switching runtime behavior, generating PDFs, exporting files, or automating actions.",
    },
    {
        "category": "Operational Travel Workspaces",
        "concept": "Operational travel workspace metadata",
        "supplementary_concept": "agency operational workspace, client/passenger summary, linked requests, trips, offers, bookings, tickets, documents, priority, assigned team, assigned agent, travel dates, operational notes",
        "current_equivalent": "OperationalTravelWorkspace, OperationalTravelWorkspaceType, OperationalTravelWorkspaceStatus, OperationalTravelWorkspacePriority, OperationalTravelWorkspaceService, /api/platform/operational-travel-workspaces, /api/agencies/{agency_id}/operational-travel-workspaces, /platform/operational-travel-workspaces, /agency/travel-workspaces",
        "status": "foundation adopted",
        "action": "Record metadata-only agency operational travel workspace records and read-only agency visibility without booking execution, ticket issuance, live GDS/NDC connectivity, payment processing, email/SMS sending, AI automation, external APIs, supplier integrations, live airline calls, background workers, or automation.",
    },
    {
        "category": "Travel Request Workspaces",
        "concept": "Travel request workspace metadata",
        "supplementary_concept": "agency request workspace, operational workspace link, requester details, client/passenger summary, requested route, requested dates, service categories, passenger count, budget, deadline, linked trips, linked offers, linked documents, internal notes",
        "current_equivalent": "TravelRequestWorkspace, TravelRequestWorkspaceType, TravelRequestWorkspaceStatus, TravelRequestWorkspacePriority, TravelRequestWorkspaceService, /api/platform/travel-request-workspaces, /api/agencies/{agency_id}/travel-request-workspaces, /platform/travel-request-workspaces, /agency/travel-requests",
        "status": "foundation adopted",
        "action": "Record metadata-only agency travel request workspace records and read-only agency visibility without booking execution, ticket issuance, live GDS/NDC connectivity, payment processing, email/SMS sending, AI automation, external APIs, supplier integrations, live airline calls, background workers, automatic trip creation, automatic offer creation, or automation.",
    },
    {
        "category": "Passenger Workspaces",
        "concept": "Passenger workspace metadata",
        "supplementary_concept": "agency passenger workspace, operational workspace link, passenger identity, travel documents, loyalty memberships, known traveler numbers, emergency contact, mobility, medical, dietary, assistance, baggage, seating, language, contact, linked requests, trips, offers, bookings, tickets, documents, internal notes",
        "current_equivalent": "PassengerWorkspace, PassengerWorkspaceStatus, PassengerWorkspaceService, /api/platform/passenger-workspaces, /api/agencies/{agency_id}/passenger-workspaces, /platform/passenger-workspaces, /agency/passenger-workspaces",
        "status": "foundation adopted",
        "action": "Record metadata-only agency passenger workspace records and read-only agency visibility without booking execution, ticket issuance, GDS/NDC connectivity, payment processing, supplier integrations, AI, email/SMS sending, background workers, external APIs, automatic profile matching, automatic document validation, airline communication, or automation.",
    },
    {
        "category": "Flight Workspaces",
        "concept": "Flight workspace metadata",
        "supplementary_concept": "agency flight workspace, operational workspace link, airline, carrier, flight number, airports, terminals, schedule, aircraft, cabin, booking class, fare family, baggage, connection, stopover, passengers, linked requests, trips, offers, bookings, tickets, documents, operational notes",
        "current_equivalent": "FlightWorkspace, FlightWorkspaceStatus, FlightWorkspaceService, /api/platform/flight-workspaces, /api/agencies/{agency_id}/flight-workspaces, /platform/flight-workspaces, /agency/flight-workspaces",
        "status": "foundation adopted",
        "action": "Record metadata-only agency flight workspace records and read-only agency visibility without booking execution, live flight search, GDS/NDC connectivity, airline APIs, payment, ticket issuance, schedule synchronization, external APIs, AI, background workers, automatic route generation, flight validation, airline lookups, live schedule updates, or automation.",
    },
    {
        "category": "Trip Workspaces",
        "concept": "Trip workspace metadata",
        "supplementary_concept": "agency trip workspace, operational workspace link, journey type, service type, client, passenger summary, flight summary, linked requests, offers, bookings, tickets, EMDs, documents, route, dates, itinerary summary, baggage summary, service summary, assigned team, operational notes",
        "current_equivalent": "TripWorkspace, TripWorkspaceStatus, TripWorkspaceService, /api/platform/trip-workspaces, /api/agencies/{agency_id}/trip-workspaces, /platform/trip-workspaces, /agency/trip-workspaces",
        "status": "foundation adopted",
        "action": "Record metadata-only agency trip workspace records and read-only agency visibility without booking execution, ticket issuance, GDS/NDC connectivity, airline APIs, payment processing, invoicing, AI, background workers, automatic trip generation, automatic itinerary generation, external integrations, external APIs, or automation.",
    },
    {
        "category": "Feature Bundle Rollout Readiness",
        "concept": "Assigned bundle readiness review metadata",
        "supplementary_concept": "rollout checklist, readiness status, warning and blocker summaries, agency read-only readiness visibility",
        "current_equivalent": "FeatureBundleRolloutReadiness, FeatureBundleRolloutChecklistItem, FeatureBundleRolloutReadinessService, /api/platform/feature-bundle-rollout-readiness, /api/agencies/{agency_id}/feature-bundle-rollout-readiness, /platform/feature-bundle-rollout-readiness, /agency/bundle-rollout-readiness",
        "status": "foundation adopted",
        "action": "Record metadata-only readiness statuses and checklists for assigned feature bundles without activating or deactivating features, enforcing access, blocking routes, changing permissions, billing, sending email or SMS, calling providers, calling external APIs, scraping, publishing, or executing rollout logic.",
    },
    {
        "category": "Feature Bundle Rollout Plans",
        "concept": "Feature bundle rollout planning metadata",
        "supplementary_concept": "rollout plan names, stages, target windows, owners, readiness snapshots, checklist summaries, agency read-only plan visibility",
        "current_equivalent": "FeatureBundleRolloutPlan, FeatureBundleRolloutPlanService, /api/platform/feature-bundle-rollout-plans, /api/agencies/{agency_id}/feature-bundle-rollout-plans, /platform/feature-bundle-rollout-plans, /agency/rollout-plans",
        "status": "foundation adopted",
        "action": "Record metadata-only rollout plan stages, target windows, owners, readiness references, assignment references, notes, and checklist summaries without activating features, enforcing access, blocking routes, publishing, sending, billing, calling providers, calling external APIs, using AI, scraping, or executing rollout logic.",
    },
    {
        "category": "Feature Bundle Rollout Approvals",
        "concept": "Feature bundle rollout approval metadata",
        "supplementary_concept": "rollout plan approvals, review status, approval notes, review timeline, agency read-only approval visibility",
        "current_equivalent": "FeatureBundleRolloutApproval, FeatureBundleRolloutApprovalSummary, FeatureBundleRolloutApprovalNote, FeatureBundleRolloutApprovalTimelineEntry, FeatureBundleRolloutApprovalService, /api/platform/feature-bundle-rollout-approvals, /api/agencies/{agency_id}/feature-bundle-rollout-approvals, /platform/feature-bundle-rollout-approvals, /agency/rollout-approval",
        "status": "foundation adopted",
        "action": "Record metadata-only approval status, notes, and timeline records for rollout plans without enabling features, enforcing permissions, gating runtime access, billing, Stripe/payment providers, authentication changes, deployment automation, cron jobs, webhooks, background workers, email/SMS/notifications, AI/OpenAI, scraping, publishing, or executing rollouts.",
    },
    {
        "category": "Feature Bundle Rollout Schedule",
        "concept": "Feature bundle rollout scheduling metadata",
        "supplementary_concept": "intended rollout timing, planned start/finish, maintenance windows, dependencies, duration, agency read-only schedule visibility",
        "current_equivalent": "FeatureBundleRolloutSchedule, FeatureBundleRolloutScheduleService, /api/platform/feature-bundle-rollout-schedule, /api/agencies/{agency_id}/feature-bundle-rollout-schedule, /platform/feature-bundle-rollout-schedule, /agency/rollout-schedule",
        "status": "foundation adopted",
        "action": "Record intended rollout timing metadata after approval review without executing rollouts, activating features, changing entitlements, modifying permissions, starting cron jobs, schedulers, workers, queues, timers, or background execution, calling external APIs, using AI, billing, or publishing automatically.",
    },
    {
        "category": "Feature Bundle Rollout Timeline",
        "concept": "Feature bundle rollout historical timeline metadata",
        "supplementary_concept": "rollout timeline entries, actors, event types, plan/agency/bundle/event/date filters, agency read-only timeline visibility",
        "current_equivalent": "FeatureBundleRolloutTimelineEntry, FeatureBundleRolloutActor, FeatureBundleRolloutEventType, FeatureBundleRolloutTimelineService, /api/platform/feature-bundle-rollout-timeline, /api/agencies/{agency_id}/feature-bundle-rollout-timeline, /platform/feature-bundle-rollout-timeline, /agency/rollout-timeline",
        "status": "foundation adopted",
        "action": "Record historical rollout event metadata with actor, timestamp, description, related-record references, and newest-first filters without enabling bundles, changing permissions, executing rollout plans, scheduling jobs, publishing, calling providers, sending email/notifications, enforcing rollout state, modifying subscriptions, or automating actions.",
    },
    {
        "category": "Rollout Dashboard",
        "concept": "Unified read-only rollout metadata dashboard",
        "supplementary_concept": "rollout dashboard, capability rollout status, readiness summary, plan summary, assigned bundle visibility",
        "current_equivalent": "RolloutDashboardSummary, RolloutDashboardSection, RolloutDashboardCounts, RolloutDashboardSnapshot, RolloutDashboardFilters, RolloutDashboardService, /api/platform/rollout-dashboard, /api/agencies/{agency_id}/rollout-dashboard, /platform/rollout-dashboard, /agency/rollout-dashboard",
        "status": "foundation adopted",
        "action": "Aggregate existing capability catalog, feature flag, feature bundle, assigned bundle, rollout readiness, and rollout plan metadata into read-only Platform Console and Agency Workspace dashboard cards without editing, activation, enforcement, route blocking, billing, automation, scheduling, sending, publishing, provider execution, external API calls, AI execution, scraping, webhooks, or rollout execution.",
    },
    {
        "category": "Capability Catalog",
        "concept": "Canonical capability inventory",
        "supplementary_concept": "capability catalogue, capability dependencies, feature/bundle references, documentation map",
        "current_equivalent": "CapabilityCatalogEntry, CapabilityCatalogService, capability_catalog, /api/platform/capabilities, /api/agencies/{agency_id}/capabilities, /platform/capabilities, /agency/capabilities",
        "status": "foundation adopted",
        "action": "Record the canonical metadata inventory of AgencyOS capabilities and their feature flag, bundle, dependency, UI route, and documentation references without enforcement, entitlement evaluation, feature activation, route blocking, billing, provider execution, publishing, external services, background workers, or AI execution.",
    },
    {
        "category": "GDS/Supplier",
        "concept": "Supplier and parser layer",
        "supplementary_concept": "supplier_endpoints, supplier_credentials, supplier_health, supplier_failover_log, gds_ai_normalizer_traces",
        "current_equivalent": "gds_parser_profiles, gds_parser_versions, gds_parser_runs, gds_parsed_entities, gds_parse_corrections, gds_parse_training_samples, gds_parser_evaluation_runs, plus provider target placeholders on booking records/workspaces; no live supplier execution",
        "status": "built",
        "action": "Use Phase 36.6 governed parser foundations; defer credentials, health, failover, and execution.",
    },
    {
        "category": "Requests/Trips/Offers/Bookings",
        "concept": "Operational workflow",
        "supplementary_concept": "trip_requests, trip_segments, offers, offer_items, bookings, pnr_snapshots",
        "current_equivalent": "request_intakes, travel_requests, request_segments, trip_dossiers, trip_segments, offer_workspaces, offer_options, offer_builder_segments, fare bundles, pricing lines, booking_workspaces, booking_records.internal_pnr_mirror_json",
        "status": "built",
        "action": "Map supplementary workflow to existing AgencyOS request/trip/offer/booking lifecycle.",
    },
    {
        "category": "Tickets/EMDs",
        "concept": "Ticket and EMD mirrors",
        "supplementary_concept": "tickets, ticket coupons, EMDs, EMD coupons",
        "current_equivalent": "ticket_records, ticket_coupons, emd_records, emd_coupons, ticket_emd_timeline_events",
        "status": "built",
        "action": "Recognize Phase 36.4 Tickets + EMD Foundation; do not create duplicate ticket or EMD models.",
    },
    {
        "category": "Documents",
        "concept": "Documents, templates, shares, designer",
        "supplementary_concept": "documents, document_versions, document_shares, document_templates, document designer",
        "current_equivalent": "document_templates, document_render_jobs, document_packages, document_share_records, rendered_documents, document_exports, document_deliveries, document_storage_records",
        "status": "built",
        "action": "Recognize Phase 36.5 document foundation; defer visual designer, version governance, public links, and automatic delivery.",
    },
    {
        "category": "AI systems",
        "concept": "Unified AI trace and ADM risk",
        "supplementary_concept": "ai_parsing_logs, ai_offerbuilder_logs, ai_pnrfix_logs, ai_debug_console_logs, ai_model_config, airline_ai_trace, adm_risk_events",
        "current_equivalent": "new AiTraceEvent and AdmRiskEvent foundations",
        "status": "add foundation now",
        "action": "Use one unified AiTraceEvent collection instead of fragmented ai_* logs; add AdmRiskEvent without implementing live AI engines.",
    },
    {
        "category": "Audit/Telemetry",
        "concept": "Audit and operational telemetry",
        "supplementary_concept": "audit_logs, error_logs, system_events, api_usage_logs",
        "current_equivalent": "audit_events plus workflow timeline events across request, booking, ticket/EMD, refund/exchange, and documents",
        "status": "built differently",
        "action": "Do not duplicate audit logs; defer formal error/api usage telemetry.",
    },
    {
        "category": "Special Services",
        "concept": "Unified special services",
        "supplementary_concept": "PassengerServiceRequest, MedicalServiceRequest, CargoLikeItem, VipServiceRequest, ExceptionRule, SSR/OSI generator, rules engine",
        "current_equivalent": "PassengerServiceRequest, request_pets, request_special_items, trip_service_items, unified_exception_rules, special_services_service, exception_engine_service, ssr_osi_generator_service, rules_and_services_registry, service catalogue mappings, canonical service taxonomy domains/families/variants/aliases, service mechanics metadata, and ancillary pricing/exception metadata",
        "status": "built differently",
        "action": "Use the lightweight special-services facade, Phase 36.8 canonical taxonomy, and Phase 36.9 service mechanics mapping; do not rebuild parallel medical/cargo/VIP modules.",
    },
    {
        "category": "Service Taxonomy",
        "concept": "Canonical special and ancillary service taxonomy",
        "supplementary_concept": "normalized service families, SSR/GDS labels, ancillary terms, policy applicability and outcomes",
        "current_equivalent": "canonical_service_domains, canonical_service_families, canonical_service_variants, airline_service_aliases, service_applicability_dimensions, service_policy_outcome_types, service_taxonomy_mapping_rules, policy_candidate_taxonomy_links, service_taxonomy_review_corrections",
        "status": "built",
        "action": "Recognize Phase 36.8 taxonomy as canonical meaning foundation; keep mechanics and execution in separate layers.",
    },
    {
        "category": "Service Mechanics",
        "concept": "SSR/OSI and EMD/RFIC/RFISC service mechanics",
        "supplementary_concept": "SSR/OSI request mechanics, recognition patterns, EMD issuance metadata, RFIC/RFISC maps, interline, lifecycle",
        "current_equivalent": "airline_service_communication_rules, ssr_osi_templates, ssr_osi_requirements, ssr_status_recognition_rules, airline_rejection_patterns, airline_service_payment_rules, airline_emd_issuance_rules, airline_rfic_rfisc_mappings, airline_emd_interline_rules, airline_emd_lifecycle_rules, policy_candidate_mechanics_links",
        "status": "foundation adopted",
        "action": "Map communication mechanics separately from payment/EMD mechanics without live SSR/OSI transmission, ticket/EMD issuance, provider execution, or agency auto-promotion.",
    },
    {
        "category": "Ancillary Pricing",
        "concept": "Ancillary pricing schema and service exception expansion",
        "supplementary_concept": "pricing rules, price components, applicability dimensions, pricing matrices, exception conditions, quote scenarios, policy candidate pricing links",
        "current_equivalent": "airline_ancillary_pricing_rules, airline_ancillary_price_components, airline_ancillary_pricing_applicability, airline_ancillary_pricing_matrices, airline_ancillary_pricing_matrix_rows, airline_service_exception_rules, airline_service_price_quote_scenarios, airline_service_price_quote_results, policy_candidate_pricing_links",
        "status": "foundation adopted",
        "action": "Use deterministic non-binding quote estimates and advisory exception metadata without invoices, payments, settlement, EMD/ticket issuance, provider execution, external AI, or agency auto-promotion.",
    },
    {
        "category": "Policy Comparison",
        "concept": "Airline policy comparison and service advisor",
        "supplementary_concept": "airline comparison matrix, service advisor, operational guidance rows, saved comparison views",
        "current_equivalent": "airline_policy_comparison_profiles, airline_policy_comparison_snapshots, airline_policy_comparison_rows, airline_service_advisor_scenarios, airline_service_advisor_results, airline_policy_comparison_saved_views",
        "status": "foundation adopted",
        "action": "Use metadata-only comparison/advisor views with deterministic complexity scoring; do not recommend airlines automatically or execute providers, EMDs, payments, invoices, accounting, or settlement.",
    },
    {
        "category": "Offer Policy Advisor",
        "concept": "Offer builder policy advisor integration",
        "supplementary_concept": "offer-linked service advisor context, offer comparison guidance, manual decision notes",
        "current_equivalent": "offer_policy_advisor_contexts, offer_policy_advisor_airline_rows, offer_policy_advisor_warnings, offer_policy_advisor_decision_notes, offer_policy_advisor_saved_snapshots",
        "status": "foundation adopted",
        "action": "Attach policy comparison, service advisor, ancillary quote, service mechanics, and taxonomy metadata to offer workspaces without automatic airline selection, offer price mutation, provider execution, EMD issuance, payment, invoice, accounting, or settlement.",
    },
    {
        "category": "Offer Decision Pack",
        "concept": "Offer builder advisor consumption and decision pack",
        "supplementary_concept": "offer decision pack, advisor evidence bundle, option review evidence, manual review notes",
        "current_equivalent": "offer_decision_packs, offer_decision_pack_options, offer_decision_pack_evidence, offer_decision_pack_warnings, offer_decision_pack_review_notes, offer_decision_pack_snapshots",
        "status": "foundation adopted",
        "action": "Consume saved advisor evidence into human-reviewed offer decision packs without automatic ranking, offer price mutation, booking, ticketing, EMD issuance, payment, invoice, accounting, settlement, or provider execution.",
    },
    {
        "category": "Offer Decision Explanation",
        "concept": "Offer explanation and decision timeline",
        "supplementary_concept": "decision explanation, evidence references, decision reasons, acknowledgements, timeline, audit snapshots",
        "current_equivalent": "offer_decision_explanations, offer_decision_timeline_events, offer_decision_evidence_references, offer_decision_reasons, offer_decision_acknowledgements, offer_decision_audit_snapshots",
        "status": "foundation adopted",
        "action": "Record human explanation and immutable audit timelines for offer decision packs without automatic recommendation, price mutation, provider execution, booking, ticketing, EMD issuance, payment, invoice, accounting, or settlement.",
    },
    {
        "category": "Offer Decision Export",
        "concept": "Offer decision pack PDF/shareable review export",
        "supplementary_concept": "review PDF export, export sections, artifacts, recipient drafts, export audit",
        "current_equivalent": "offer_decision_exports, offer_decision_export_sections, offer_decision_export_artifacts, offer_decision_export_recipient_drafts, offer_decision_export_audit_events",
        "status": "foundation adopted",
        "action": "Create metadata-only review export records for decision packs and explanations without automatic sending, public links, recommendations, offer price mutation, provider execution, booking, ticketing, EMD issuance, payment, invoice, accounting, or settlement.",
    },
    {
        "category": "Offer Decision Export Preview",
        "concept": "Offer decision export render preview",
        "supplementary_concept": "render preview, preview sections, preview blocks, validation checks, immutable preview snapshots",
        "current_equivalent": "offer_decision_export_previews, offer_decision_export_preview_sections, offer_decision_export_preview_blocks, offer_decision_export_preview_validations, offer_decision_export_preview_snapshots",
        "status": "foundation adopted",
        "action": "Create metadata-only render preview records for offer decision exports without real PDF delivery, automatic sending, public links, recommendations, offer price mutation, provider execution, booking, ticketing, EMD issuance, payment, invoice, accounting, or settlement.",
    },
    {
        "category": "Offer Decision Export Release Readiness",
        "concept": "Offer decision export approval and manual release readiness",
        "supplementary_concept": "approval gates, release readiness, release holds, immutable release snapshots",
        "current_equivalent": "offer_decision_export_approvals, offer_decision_export_approval_checkpoints, offer_decision_export_release_readiness, offer_decision_export_release_holds, offer_decision_export_release_snapshots",
        "status": "foundation adopted",
        "action": "Create metadata-only human approval gates, checkpoints, release readiness records, holds, and immutable release snapshots without real PDF delivery, automatic sending, public links, recommendations, offer price mutation, provider execution, booking, ticketing, EMD issuance, payment, invoice, accounting, or settlement.",
    },
    {
        "category": "Offer Decision Export Delivery Handoff",
        "concept": "Offer decision export manual delivery handoff",
        "supplementary_concept": "manual handoff workspace, recipient handoff metadata, attachment metadata, instructions, immutable handoff snapshots",
        "current_equivalent": "offer_decision_export_delivery_handoffs, offer_decision_export_delivery_recipients, offer_decision_export_delivery_attachments, offer_decision_export_delivery_instructions, offer_decision_export_delivery_snapshots",
        "status": "foundation adopted",
        "action": "Create metadata-only manual handoff records without email/SMS sending, SMTP/SMS/storage provider calls, public links, real PDF delivery, recommendations, offer price mutation, provider execution, booking, PNR mutation, ticketing, EMD issuance, payment, invoice, accounting, or settlement.",
    },
    {
        "category": "Offer Decision Export Delivery Outcome",
        "concept": "Offer decision export manual delivery outcome tracking",
        "supplementary_concept": "manual delivery outcome status, outcome events, receipts, issues, immutable outcome snapshots",
        "current_equivalent": "offer_decision_export_delivery_outcomes, offer_decision_export_delivery_outcome_events, offer_decision_export_delivery_receipts, offer_decision_export_delivery_issues, offer_decision_export_delivery_outcome_snapshots",
        "status": "foundation adopted",
        "action": "Create metadata-only human-recorded outcome tracking without email/SMS sending, public links, real PDF delivery, recommendations, offer price mutation, provider execution, booking, PNR mutation, ticketing, EMD issuance, payment, invoice, accounting, or settlement.",
    },
    {
        "category": "Offer Decision Export Audit Review",
        "concept": "Offer decision export audit review",
        "supplementary_concept": "lifecycle audit review, findings, checklist items, immutable review snapshots",
        "current_equivalent": "offer_decision_export_audit_reviews, offer_decision_export_audit_review_findings, offer_decision_export_audit_review_checklist_items, offer_decision_export_audit_review_snapshots",
        "status": "foundation adopted",
        "action": "Create metadata-only lifecycle audit reviews over decision packs, explanations, exports, previews, release readiness, manual handoffs, manual outcomes, unresolved issues, and snapshot coverage without email/SMS sending, public links, real PDF delivery, recommendations, offer price mutation, provider execution, booking, PNR mutation, ticketing, EMD issuance, payment, invoice, accounting, or settlement.",
    },
    {
        "category": "Offer Decision Export Governance",
        "concept": "Offer decision export governance",
        "supplementary_concept": "governance records, retention policies, legal bases, archive status, governance exceptions, immutable governance snapshots",
        "current_equivalent": "offer_decision_export_governance_records, offer_decision_export_governance_rules, offer_decision_export_retention_policies, offer_decision_export_legal_bases, offer_decision_export_archive_statuses, offer_decision_export_governance_exceptions, offer_decision_export_governance_snapshots",
        "status": "foundation adopted",
        "action": "Create metadata-only export governance records without email/SMS sending, public links, real PDF delivery, offer or price mutation, recommendation, provider execution, booking, PNR mutation, ticketing, EMD issuance, payment, invoice, accounting, settlement, scraping, or external AI.",
    },
    {
        "category": "Offer Decision Export Compliance",
        "concept": "Offer decision export compliance evidence",
        "supplementary_concept": "compliance evidence, requirements, checks, pass/fail results, exceptions, immutable compliance snapshots",
        "current_equivalent": "offer_decision_export_compliance_evidence, offer_decision_export_compliance_requirements, offer_decision_export_compliance_checks, offer_decision_export_compliance_results, offer_decision_export_compliance_exceptions, offer_decision_export_compliance_snapshots",
        "status": "foundation adopted",
        "action": "Create metadata-only export compliance evidence without email/SMS sending, public links, real PDF delivery, offer or price mutation, recommendation, provider execution, booking, PNR mutation, ticketing, EMD issuance, payment, invoice, accounting, settlement, GDS execution, scraping, or external AI.",
    },
    {
        "category": "Routes",
        "concept": "Route roots",
        "supplementary_concept": "/agent/* and /admin/* route shells",
        "current_equivalent": "/agency/* and /platform/*",
        "status": "intentionally rejected",
        "action": "Keep /agency and /platform canonical; do not introduce /agent or /admin roots.",
    },
    {
        "category": "Booking UX",
        "concept": "Booking workspace creation entry point",
        "supplementary_concept": "booking workflow create/open action",
        "current_equivalent": "/agency/booking-workspaces with readiness, manual booking, and import entry points",
        "status": "built",
        "action": "Recognize accepted-offer readiness, standalone manual, import, and existing-trip change booking paths.",
    },
    {
        "category": "Standalone/Import/Change",
        "concept": "Non-linear agency booking workflows",
        "supplementary_concept": "manual bookings, imported confirmations, existing trip changes, exchanges, reissues",
        "current_equivalent": "BookingImportDraft, TripChangeOperation, TicketExchangeOperation, EmdExchangeOperation, source-context fields",
        "status": "built",
        "action": "Adopt as internal mirror foundations without provider execution, live exchange, refund, void, or payment actions.",
    },
]


ROUTE_POLICY: dict[str, Any] = {
    "canonical_routes": [
        {"root": "/platform/*", "purpose": "Platform owner and global governance/configuration UI."},
        {"root": "/agency/*", "purpose": "Agency operational workspace UI."},
        {"root": "/api/platform/*", "purpose": "Platform owner governance APIs."},
        {"root": "/api/agencies/{agency_id}/*", "purpose": "Agency operational APIs."},
        {"root": "/api/reference/*", "purpose": "Shared consume APIs."},
    ],
    "rejected_routes": [
        {"root": "/agent/*", "reason": "Duplicates the existing agency workspace route root."},
        {"root": "/admin/*", "reason": "Duplicates the existing platform owner route root."},
    ],
    "route_mappings": [
        {"supplementary": "/agent/clients", "agencyos": "/agency/clients"},
        {"supplementary": "/agent/trip-requests", "agencyos": "/agency/requests and /agency/trips"},
        {"supplementary": "/agent/parser", "agencyos": "/agency/gds-parser"},
        {"supplementary": "/agent/parser/imports", "agencyos": "/agency/booking-imports and /agency/gds-parser"},
        {"supplementary": "/admin/airline-data-packs", "agencyos": "/platform/airline-intelligence-data-packs"},
        {"supplementary": "/admin/airline-data-pack-reviews", "agencyos": "/platform/airline-intelligence-data-pack-reviews"},
        {"supplementary": "/admin/airline-knowledge-versions", "agencyos": "/platform/airline-intelligence-knowledge-versions"},
        {"supplementary": "/admin/airline-agency-consumption", "agencyos": "/platform/airline-intelligence-agency-consumption"},
        {"supplementary": "/agent/airline-coverage", "agencyos": "/agency/airline-intelligence-coverage"},
        {"supplementary": "/agent/airline-review-coverage", "agencyos": "/agency/airline-intelligence-review-coverage"},
        {"supplementary": "/agent/airline-knowledge-versions", "agencyos": "/agency/airline-intelligence-knowledge-versions"},
        {"supplementary": "/agent/airline-intelligence-usage", "agencyos": "/agency/airline-intelligence-consumption"},
        {"supplementary": "/admin/exception-rules", "agencyos": "/platform/rules-services"},
        {"supplementary": "/admin/special-services", "agencyos": "/platform/rules-services"},
        {"supplementary": "/admin/ancillary-pricing", "agencyos": "/platform/ancillary-pricing"},
        {"supplementary": "/agent/ancillary-pricing", "agencyos": "/agency/ancillary-pricing"},
        {"supplementary": "/admin/policy-comparison", "agencyos": "/platform/policy-comparison"},
        {"supplementary": "/agent/policy-comparison", "agencyos": "/agency/policy-comparison"},
        {"supplementary": "/agent/service-advisor", "agencyos": "/agency/airline-service-advisor"},
        {"supplementary": "/admin/offer-advisor", "agencyos": "/platform/offer-policy-advisor"},
        {"supplementary": "/agent/offer-advisor", "agencyos": "/agency/offer-policy-advisor"},
        {"supplementary": "/admin/offer-decision-packs", "agencyos": "/platform/offer-decision-packs"},
        {"supplementary": "/agent/offer-decision-packs", "agencyos": "/agency/offer-decision-packs"},
        {"supplementary": "/admin/offer-decision-explanations", "agencyos": "/platform/offer-decision-explanations"},
        {"supplementary": "/agent/offer-decision-explanations", "agencyos": "/agency/offer-decision-explanations"},
        {"supplementary": "/admin/offer-decision-exports", "agencyos": "/platform/offer-decision-exports"},
        {"supplementary": "/agent/offer-decision-exports", "agencyos": "/agency/offer-decision-exports"},
        {"supplementary": "/admin/offer-decision-export-previews", "agencyos": "/platform/offer-decision-export-previews"},
        {"supplementary": "/agent/offer-decision-export-previews", "agencyos": "/agency/offer-decision-export-previews"},
        {"supplementary": "/admin/offer-decision-export-releases", "agencyos": "/platform/offer-decision-export-releases"},
        {"supplementary": "/agent/offer-decision-export-releases", "agencyos": "/agency/offer-decision-export-releases"},
        {"supplementary": "/admin/offer-decision-export-deliveries", "agencyos": "/platform/offer-decision-export-deliveries"},
        {"supplementary": "/agent/offer-decision-export-deliveries", "agencyos": "/agency/offer-decision-export-deliveries"},
        {"supplementary": "/admin/offer-decision-export-delivery-outcomes", "agencyos": "/platform/offer-decision-export-delivery-outcomes"},
        {"supplementary": "/agent/offer-decision-export-delivery-outcomes", "agencyos": "/agency/offer-decision-export-delivery-outcomes"},
        {"supplementary": "/admin/offer-decision-export-audit-reviews", "agencyos": "/platform/offer-decision-export-audit-reviews"},
        {"supplementary": "/agent/offer-decision-export-audit-reviews", "agencyos": "/agency/offer-decision-export-audit-reviews"},
        {"supplementary": "/admin/offer-decision-export-governance", "agencyos": "/platform/offer-decision-export-governance"},
        {"supplementary": "/agent/offer-decision-export-governance", "agencyos": "/agency/offer-decision-export-governance"},
        {"supplementary": "/admin/offer-decision-export-compliance", "agencyos": "/platform/offer-decision-export-compliance"},
        {"supplementary": "/agent/offer-decision-export-compliance", "agencyos": "/agency/offer-decision-export-compliance"},
        {"supplementary": "/admin/feature-flag-bundles", "agencyos": "/platform/feature-flag-bundles"},
        {"supplementary": "/agent/feature-bundles", "agencyos": "/agency/feature-bundles"},
        {"supplementary": "/admin/feature-bundle-assignments", "agencyos": "/platform/feature-bundle-assignments"},
        {"supplementary": "/agent/assigned-bundles", "agencyos": "/agency/assigned-bundles"},
        {"supplementary": "/admin/feature-bundle-dependencies", "agencyos": "/platform/feature-bundle-dependencies"},
        {"supplementary": "/agent/bundle-dependencies", "agencyos": "/agency/bundle-dependencies"},
        {"supplementary": "/admin/feature-bundle-rollout-risks", "agencyos": "/platform/feature-bundle-rollout-risks"},
        {"supplementary": "/agent/rollout-risks", "agencyos": "/agency/rollout-risks"},
        {"supplementary": "/admin/feature-bundle-rollout-issues", "agencyos": "/platform/feature-bundle-rollout-issues"},
        {"supplementary": "/agent/rollout-issues", "agencyos": "/agency/rollout-issues"},
        {"supplementary": "/admin/feature-bundle-rollout-decisions", "agencyos": "/platform/feature-bundle-rollout-decisions"},
        {"supplementary": "/agent/rollout-decisions", "agencyos": "/agency/rollout-decisions"},
        {"supplementary": "/admin/feature-bundle-rollout-change-requests", "agencyos": "/platform/feature-bundle-rollout-change-requests"},
        {"supplementary": "/agent/rollout-change-requests", "agencyos": "/agency/rollout-change-requests"},
        {"supplementary": "/admin/feature-bundle-rollout-rollback-plans", "agencyos": "/platform/feature-bundle-rollout-rollback-plans"},
        {"supplementary": "/agent/rollout-rollback-plans", "agencyos": "/agency/rollout-rollback-plans"},
        {"supplementary": "/admin/feature-bundle-rollout-summary-packs", "agencyos": "/platform/feature-bundle-rollout-summary-packs"},
        {"supplementary": "/agent/rollout-summary-packs", "agencyos": "/agency/rollout-summary-packs"},
        {"supplementary": "/admin/operational-travel-workspaces", "agencyos": "/platform/operational-travel-workspaces"},
        {"supplementary": "/agent/travel-workspaces", "agencyos": "/agency/travel-workspaces"},
        {"supplementary": "/admin/travel-request-workspaces", "agencyos": "/platform/travel-request-workspaces"},
        {"supplementary": "/agent/travel-requests", "agencyos": "/agency/travel-requests"},
        {"supplementary": "/admin/passenger-workspaces", "agencyos": "/platform/passenger-workspaces"},
        {"supplementary": "/agent/passenger-workspaces", "agencyos": "/agency/passenger-workspaces"},
        {"supplementary": "/admin/flight-workspaces", "agencyos": "/platform/flight-workspaces"},
        {"supplementary": "/agent/flight-workspaces", "agencyos": "/agency/flight-workspaces"},
        {"supplementary": "/admin/trip-workspaces", "agencyos": "/platform/trip-workspaces"},
        {"supplementary": "/agent/trip-workspaces", "agencyos": "/agency/trip-workspaces"},
        {"supplementary": "/admin/feature-bundle-rollout-readiness", "agencyos": "/platform/feature-bundle-rollout-readiness"},
        {"supplementary": "/agent/bundle-rollout-readiness", "agencyos": "/agency/bundle-rollout-readiness"},
        {"supplementary": "/admin/feature-bundle-rollout-plans", "agencyos": "/platform/feature-bundle-rollout-plans"},
        {"supplementary": "/agent/rollout-plans", "agencyos": "/agency/rollout-plans"},
        {"supplementary": "/admin/feature-bundle-rollout-approvals", "agencyos": "/platform/feature-bundle-rollout-approvals"},
        {"supplementary": "/agent/rollout-approval", "agencyos": "/agency/rollout-approval"},
        {"supplementary": "/admin/feature-bundle-rollout-schedule", "agencyos": "/platform/feature-bundle-rollout-schedule"},
        {"supplementary": "/agent/rollout-schedule", "agencyos": "/agency/rollout-schedule"},
        {"supplementary": "/admin/feature-bundle-rollout-timeline", "agencyos": "/platform/feature-bundle-rollout-timeline"},
        {"supplementary": "/agent/rollout-timeline", "agencyos": "/agency/rollout-timeline"},
        {"supplementary": "/admin/rollout-dashboard", "agencyos": "/platform/rollout-dashboard"},
        {"supplementary": "/agent/rollout-dashboard", "agencyos": "/agency/rollout-dashboard"},
        {"supplementary": "/admin/capabilities", "agencyos": "/platform/capabilities"},
        {"supplementary": "/agent/capabilities", "agencyos": "/agency/capabilities"},
        {"supplementary": "/documents", "agencyos": "/agency/documents and /platform/document-templates"},
        {"supplementary": "/admin/parser", "agencyos": "/platform/gds-parser"},
        {"supplementary": "/tickets", "agencyos": "/agency/tickets-emds"},
        {"supplementary": "/bookings", "agencyos": "/agency/booking-workspaces"},
        {"supplementary": "/changes or /exchanges", "agencyos": "/agency/trips/{trip_id} and /agency/tickets-emds"},
    ],
    "aliases_added": False,
}


NEXT_PHASE_RECOMMENDATIONS: list[dict[str, str]] = [
    {
        "phase": "Phase 37",
        "title": "Provider Import And Issuance Provenance",
        "reason": "Document and governed parser foundations are now in place; the next gap is provider import provenance and reconciliation around booking, ticket, and EMD mirrors.",
    },
    {
        "phase": "Phase 39.10",
        "title": "Airline Intelligence Promotion Governance Hardening",
        "reason": "Airline intelligence agency consumption is now visible as metadata; any future operational promotion still needs explicit migration governance.",
    },
    {
        "phase": "Phase 37.8",
        "title": "Special Services UX Unification",
        "reason": "The facade keeps current services canonical while future UI can unify medical, cargo, VIP, and PRM flows.",
    },
    {
        "phase": "Phase 37.8",
        "title": "AI Trace / ADM Risk Console",
        "reason": "AiTraceEvent and AdmRiskEvent foundations need an operator review console before any automation.",
    },
    {
        "phase": "Phase 38",
        "title": "Live Provider/Supplier Execution Planning",
        "reason": "Provider execution must remain disabled by default until explicit integration governance is designed.",
    },
]


def get_blueprint_adoption_map() -> dict[str, Any]:
    return {
        "phase": PHASE_LABEL,
        "items": ADOPTION_ITEMS,
        "statuses": ["built", "built differently", "partially built", "add foundation now", "planned later", "intentionally rejected"],
        "tickets_emd_foundation": "built in Phase 36.4",
        "booking_workspace_creation_entrypoint": "fixed after Phase 36.4",
    }


def get_blueprint_route_policy() -> dict[str, Any]:
    return {"phase": PHASE_LABEL, **ROUTE_POLICY}


def get_blueprint_gap_summary() -> dict[str, Any]:
    return {
        "phase": PHASE_LABEL,
        "foundations_added_now": [
            "AiTraceEvent",
            "AdmRiskEvent",
            "GdsParseSample",
            "AirlineBrandAsset",
            "Blueprint adoption governance API/UI",
            "SpecialServicesUnifiedFacade",
            "BookingImportDraft",
            "TripChangeOperation",
            "TicketExchangeOperation",
            "EmdExchangeOperation",
            "DocumentRenderJob",
            "DocumentPackage",
            "DocumentShareRecord",
            "DocumentContextService and DocumentRenderService",
            "GdsParserProfile",
            "GdsParserVersion",
            "GdsParserRun",
            "GdsParsedEntity",
            "GdsParseCorrection",
            "GdsParseTrainingSample",
            "GdsParserEvaluationRun",
            "CanonicalServiceDomain",
            "CanonicalServiceFamily",
            "CanonicalServiceVariant",
            "AirlineServiceAlias",
            "ServiceApplicabilityDimension",
            "ServicePolicyOutcomeType",
            "ServiceTaxonomyMappingRule",
            "PolicyCandidateTaxonomyLink",
            "ServiceTaxonomyReviewCorrection",
            "AirlineIntelligenceDataPack",
            "AirlineIntelligenceDataPackItem",
            "AirlineIntelligenceDataPackValidationIssue",
            "AirlineIntelligenceDataPackImportRun",
            "AirlineIntelligenceDataPackReviewNote",
            "AirlineIntelligenceCoverageSnapshot",
            "AirlineIntelligenceDataPackReview",
            "AirlineIntelligenceDataPackReviewChecklistItem",
            "AirlineIntelligenceDataPackFieldMapping",
            "AirlineIntelligenceDataPackConflict",
            "AirlineIntelligenceDataPackPromotionReadiness",
            "AirlineIntelligenceDataPackReviewSnapshot",
            "AirlineIntelligenceKnowledgeVersion",
            "AirlineIntelligenceKnowledgeVersionItem",
            "AirlineIntelligenceKnowledgeReleaseChannel",
            "AirlineIntelligenceKnowledgeReleaseAssignment",
            "AirlineIntelligenceKnowledgeVersionComparison",
            "AirlineIntelligenceKnowledgeRollbackPlan",
            "AirlineIntelligenceKnowledgeVersionSnapshot",
            "AirlineIntelligenceAgencyConsumptionProfile",
            "AirlineIntelligenceAgencyKnowledgeAssignmentView",
            "AirlineIntelligenceAgencyUsageReadiness",
            "AirlineIntelligenceAgencyConsumptionNote",
            "AirlineIntelligenceAgencyConsumptionSnapshot",
            "SaaSSubscriptionPlan",
            "SaaSPlanEntitlement",
            "AgencySubscriptionAssignment",
            "AgencyEntitlementReadiness",
            "AgencySubscriptionReviewNote",
            "AgencySubscriptionSnapshot",
            "AgencyFeatureFlag",
            "AgencyFeatureFlagReview",
            "AgencyFeatureFlagSnapshot",
            "AgencyFeatureFlagAudit",
            "AgencyFeatureFlagReadiness",
            "FeatureFlagBundle",
            "FeatureFlagBundleSummary",
            "FeatureFlagBundleReview",
            "FeatureFlagBundleMember",
            "BundleReadiness",
            "AgencyFeatureBundleAssignment",
            "AgencyFeatureBundleAssignmentHistory",
            "FeatureBundleDependency",
            "FeatureBundleDependencyReference",
            "FeatureBundleDependencyType",
            "FeatureBundleRolloutRisk",
            "FeatureBundleRolloutRiskImpact",
            "FeatureBundleRolloutRiskLikelihood",
            "FeatureBundleRolloutRiskStatus",
            "FeatureBundleRolloutIssue",
            "FeatureBundleRolloutIssueSeverity",
            "FeatureBundleRolloutIssueStatus",
            "FeatureBundleRolloutDecision",
            "FeatureBundleRolloutDecisionCategory",
            "FeatureBundleRolloutDecisionStatus",
            "FeatureBundleRolloutChangeRequest",
            "FeatureBundleRolloutChangeRequestType",
            "FeatureBundleRolloutChangeRequestPriority",
            "FeatureBundleRolloutChangeRequestImpactLevel",
            "FeatureBundleRolloutChangeRequestStatus",
            "FeatureBundleRolloutReadiness",
            "FeatureBundleRolloutChecklistItem",
            "FeatureBundleRolloutPlan",
            "FeatureBundleRolloutApproval",
            "FeatureBundleRolloutApprovalSummary",
            "FeatureBundleRolloutApprovalNote",
            "FeatureBundleRolloutApprovalTimelineEntry",
            "FeatureBundleRolloutSchedule",
            "FeatureBundleRolloutTimelineEntry",
            "FeatureBundleRolloutActor",
            "FeatureBundleRolloutEventType",
            "RolloutDashboardSummary",
            "RolloutDashboardSection",
            "RolloutDashboardCounts",
            "RolloutDashboardSnapshot",
            "RolloutDashboardFilters",
            "CapabilityCatalogEntry",
        ],
        "already_built": [
            "Rules & Services foundation",
            "Rule-aware offer builder",
            "Offer acceptance and booking readiness",
            "Booking workspace and BookingRecord/PNR mirror foundation",
            "Tickets + EMD Foundation built in Phase 36.4",
            "Booking workspace creation entry point fixed after Phase 36.4",
            "Standalone booking, import draft, and existing-trip change/exchange foundations built in Phase 36.4.6",
            "Document foundation built in Phase 36.5",
            "GDS parser foundation and training samples built in Phase 36.6",
            "Airline policy ingestion source, extraction, review, and approved knowledge foundation built in Phase 36.7",
            "Canonical special and ancillary service taxonomy foundation built in Phase 36.8",
            "SSR/OSI and EMD/RFIC/RFISC service mechanics mapping foundation built in Phase 36.9",
            "Ancillary pricing schema and exception engine expansion foundation built in Phase 37.0",
            "Policy comparison and service advisor foundation built in Phase 37.1",
            "Offer builder policy advisor integration foundation built in Phase 37.2",
            "Offer builder advisor consumption and decision pack foundation built in Phase 37.3",
            "Offer explanation and decision timeline foundation built in Phase 37.4",
            "Offer decision export foundation built in Phase 37.5",
            "Offer decision export preview foundation built in Phase 37.6",
            "Offer decision export release readiness foundation built in Phase 37.7",
            "Offer decision export manual delivery handoff foundation built in Phase 37.8",
            "Offer decision export manual delivery outcome tracking foundation built in Phase 37.9",
            "Offer decision export audit review foundation built in Phase 38.0",
            "Offer decision export governance foundation built in Phase 38.1",
            "Offer decision export compliance evidence foundation built in Phase 38.2",
            "Airline intelligence data pack foundation built in Phase 39.0",
            "Airline intelligence data pack review and promotion-readiness foundation built in Phase 39.1",
            "Airline intelligence knowledge versioning and publication-control foundation built in Phase 39.2",
            "Airline intelligence agency consumption bridge built in Phase 39.3",
            "Platform / agency UX consolidation built in Phase 39.4",
            "SaaS subscription and entitlement foundation built in Phase 39.5",
            "Subscription entitlement UI guardrails built in Phase 39.6",
            "Agency feature flags foundation built in Phase 39.7",
            "Agency feature flag audit foundation built in Phase 39.8",
            "Feature flag bundles foundation built in Phase 39.9",
            "Feature bundle assignment foundation built in Phase 40.0",
            "Feature bundle dependency foundation built in Phase 40.7",
            "Feature bundle rollout readiness foundation built in Phase 40.1",
            "Feature bundle rollout plan foundation built in Phase 40.2",
            "Rollout dashboard foundation built in Phase 40.3",
            "Feature bundle rollout approval foundation built in Phase 40.4",
            "Feature bundle rollout schedule foundation built in Phase 40.5",
            "Feature bundle rollout timeline foundation built in Phase 40.6",
            "Capability catalog foundation built in Phase 40.1",
        ],
        "deferred": [
            "Full visual document designer, document version governance, public sharing links, automatic delivery, and e-signature",
            "Full GDS grammar coverage, provider reconciliation, and live supplier execution",
            "Live SSR/OSI transmission, live ticket/EMD issuance, automatic airline recommendation, and provider-priced reconciliation",
            "Visual airline dashboards",
            "Live AI engines and model configuration console",
            "Supplier credentials, health, failover, and execution",
            "Payment, invoice/accounting expansion, and settlement",
        ],
        "intentionally_rejected": [
            "/agent/* route root",
            "/admin/* route root",
            "Parallel RBAC model",
            "Parallel trip/request/offer/booking/ticket/EMD models",
            "Supabase, Next.js, or Horizons-specific architecture migration",
        ],
        "next_immediate_phase": "Phase 37 - Provider Import And Issuance Provenance",
        "gap_count": 6,
        "rejected_route_count": len(ROUTE_POLICY["rejected_routes"]),
    }


def get_next_phase_recommendations() -> dict[str, Any]:
    return {"phase": PHASE_LABEL, "items": NEXT_PHASE_RECOMMENDATIONS}
