import { useEffect, useState } from "react"
import GitCompareArrows from "lucide-react/dist/esm/icons/git-compare-arrows.js"
import RefreshCw from "lucide-react/dist/esm/icons/refresh-cw.js"
import ShieldCheck from "lucide-react/dist/esm/icons/shield-check.js"
import TriangleAlert from "lucide-react/dist/esm/icons/triangle-alert.js"
import ProtectedRoute from "../../components/ProtectedRoute"
import PlatformLayout from "../../layouts/PlatformLayout"
import { apiGet } from "../../lib/api"

export default function JourneyOptionCompositionDiagnosticsPage() {
  const [state, setState] = useState(null)
  const [error, setError] = useState("")
  async function load() { const [me, dashboard] = await Promise.all([apiGet("/api/auth/me"), apiGet("/api/platform/journey-option-compositions")]); setState({ me, dashboard }) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  const summary = state?.dashboard?.summary || {}
  const metrics = [["Compositions", summary.composition_count], ["Active", summary.active_composition_count], ["Incomplete", summary.incomplete_composition_count], ["Review required", summary.review_required_composition_count], ["Options", summary.itinerary_option_count], ["Fare choices", summary.fare_brand_choice_count], ["Finalized snapshots", summary.finalized_snapshot_count], ["Offer handoffs", summary.offer_handoff_count]]
  return <PlatformLayout user={state?.me?.user}><ProtectedRoute loading={!state && !error} error={error}><div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase text-blue-700">Journey Engine Governance</p><h1 className="mt-2 text-2xl font-semibold text-slate-950">Journey Option Composition Diagnostics</h1><p className="mt-1 max-w-4xl text-sm text-slate-600">Read-only diagnostics for itinerary alternatives, fare-brand choices, arithmetic validation, advisory service review, immutable composition snapshots, and explicit offer handoffs.</p></div><button type="button" title="Refresh diagnostics" onClick={() => load().catch((err) => setError(err.message))} className="icon-button"><RefreshCw className="h-4 w-4" /></button></header><div className="border-y border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900"><strong>Governance view only.</strong> Platform users cannot edit agency compositions here. No live pricing, availability, provider connectivity, publication, booking, ticketing, or EMD execution is available.</div><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <Metric label={label} value={value || 0} key={label} />)}</section><section className="grid gap-6 lg:grid-cols-3"><Panel icon={GitCompareArrows} title="Composition mix" rows={summary.status_counts} /><Panel icon={TriangleAlert} title="Warning severity" rows={summary.warning_severity_counts} /><Panel icon={ShieldCheck} title="Provenance" rows={{ manual_fare_choices: summary.manual_fare_brand_choice_count, governed_imports: summary.imported_fare_brand_choice_count, price_breakdowns: summary.price_breakdown_count, service_assessments: summary.service_assessment_count }} /></section><section><h2 className="text-lg font-semibold text-slate-950">Recent compositions</h2><div className="mt-3 overflow-x-auto border-y border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><tr><th className="px-3 py-3">Agency</th><th className="px-3 py-3">Composition</th><th className="px-3 py-3">Journey</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Completeness</th><th className="px-3 py-3">Updated</th></tr></thead><tbody className="divide-y divide-slate-100">{(state?.dashboard?.items || []).map((item) => <tr key={item.id}><td className="px-3 py-3">{item.agency_id}</td><td className="px-3 py-3 font-semibold">{item.title}</td><td className="px-3 py-3">{item.journey_id}</td><td className="px-3 py-3">{title(item.status)}</td><td className="px-3 py-3">{item.completeness_score || 0}%</td><td className="px-3 py-3">{dateTime(item.updated_at)}</td></tr>)}</tbody></table></div></section></div></ProtectedRoute></PlatformLayout>
}

function Metric({ label, value }) { return <div className="rounded-md border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{value}</p></div> }
function Panel({ icon: Icon, title: heading, rows = {} }) { return <section><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-blue-700" /><h2 className="font-semibold text-slate-950">{heading}</h2></div><dl className="mt-3 divide-y divide-slate-200 border-y border-slate-200">{Object.entries(rows).map(([label, value]) => <div className="flex justify-between gap-3 py-3" key={label}><dt className="text-sm text-slate-600">{title(label)}</dt><dd className="font-semibold text-slate-950">{value || 0}</dd></div>)}</dl></section> }
function title(value) { return String(value || "Unknown").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()) }
function dateTime(value) { return value ? new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "Unknown" }
