import { useEffect, useState } from "react"
import CheckCircle2 from "lucide-react/dist/esm/icons/check-circle-2.js"
import Clock3 from "lucide-react/dist/esm/icons/clock-3.js"
import FileStack from "lucide-react/dist/esm/icons/files.js"
import RefreshCw from "lucide-react/dist/esm/icons/refresh-cw.js"
import ShieldCheck from "lucide-react/dist/esm/icons/shield-check.js"
import ProtectedRoute from "../../components/ProtectedRoute"
import PlatformLayout from "../../layouts/PlatformLayout"
import { apiGet } from "../../lib/api"

export default function OfferDeliveryDiagnosticsPage() {
  const [state, setState] = useState(null)
  const [error, setError] = useState("")
  async function load() { const [me, dashboard] = await Promise.all([apiGet("/api/auth/me"), apiGet("/api/platform/offer-delivery-diagnostics")]); setState({ me, dashboard }) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  const summary = state?.dashboard?.summary || {}
  const metrics = [["Deliveries", summary.delivery_count], ["Released", summary.released_delivery_count], ["Versions", summary.delivery_version_count], ["Recipients", summary.authorized_recipient_count], ["Interactions", summary.client_interaction_count], ["Decisions", summary.decision_count], ["Acceptance links", summary.completed_acceptance_handoff_count], ["Document packages", summary.document_package_link_count]]
  return <PlatformLayout user={state?.me?.user}><ProtectedRoute loading={!state && !error} error={error}><div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase text-blue-700">Offer Governance</p><h1 className="mt-2 text-2xl font-semibold text-slate-950">Offer Delivery Diagnostics</h1><p className="mt-1 max-w-4xl text-sm text-slate-600">Read-only source-integrity, tenant-isolation, version, recipient, decision, acceptance, and document-package diagnostics.</p></div><button type="button" title="Refresh diagnostics" className="icon-button" onClick={() => load().catch((err) => setError(err.message))}><RefreshCw className="h-4 w-4" /></button></header><div className="border-y border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900"><strong>Governance view only.</strong> Platform users cannot impersonate recipients or submit client decisions. No live fares, public links, provider operations, payments, bookings, tickets, or automatic messages are enabled.</div><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <Metric key={label} label={label} value={value || 0} />)}</section><section className="grid gap-6 lg:grid-cols-3"><Panel icon={ShieldCheck} title="Delivery status" rows={summary.status_counts} /><Panel icon={CheckCircle2} title="Decision types" rows={summary.decision_type_counts} /><Panel icon={Clock3} title="Governance signals" rows={{ blocking_validations: summary.blocking_validation_count, unknown_values: summary.unknown_value_count, expired: summary.expired_delivery_count, revoked: summary.revoked_delivery_count }} /></section><section><div className="flex items-center gap-2"><FileStack className="h-5 w-5 text-blue-700" /><h2 className="text-lg font-semibold text-slate-950">Recent deliveries</h2></div><div className="mt-3 overflow-x-auto border-y border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><tr><th className="px-3 py-3">Agency</th><th className="px-3 py-3">Delivery</th><th className="px-3 py-3">Comparison</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Released</th><th className="px-3 py-3">Expires</th></tr></thead><tbody className="divide-y divide-slate-100">{(state?.dashboard?.items || []).map((item) => <tr key={item.id}><td className="px-3 py-3">{item.agency_id}</td><td className="px-3 py-3 font-semibold">{item.delivery_code}</td><td className="px-3 py-3">{item.presentation_id}</td><td className="px-3 py-3">{title(item.status)}</td><td className="px-3 py-3">{dateTime(item.released_at)}</td><td className="px-3 py-3">{dateTime(item.expires_at)}</td></tr>)}</tbody></table></div></section></div></ProtectedRoute></PlatformLayout>
}
function Metric({ label, value }) { return <div className="rounded-md border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{value}</p></div> }
function Panel({ icon: Icon, title: heading, rows = {} }) { return <section><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-blue-700" /><h2 className="font-semibold text-slate-950">{heading}</h2></div><dl className="mt-3 divide-y divide-slate-200 border-y border-slate-200">{Object.entries(rows || {}).map(([label, value]) => <div className="flex justify-between gap-3 py-3" key={label}><dt className="text-sm text-slate-600">{title(label)}</dt><dd className="font-semibold text-slate-950">{value || 0}</dd></div>)}</dl></section> }
function title(value) { return String(value || "Unknown").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()) }
function dateTime(value) { return value ? new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "Not set" }
