export const platformModuleGroups = [
  {
    title: "SaaS & Agencies",
    description: "Platform owners manage subscribed agencies, account setup, and the overall SaaS operating layer.",
    audience: "Platform only",
    safety: "Metadata only",
    items: [
      { label: "Platform Console", description: "Owner overview and system counts", href: "/platform", icon: "shield", badge: "Platform only" },
      { label: "Operational Travel Workspaces", description: "Travel workspace metadata", href: "/platform/operational-travel-workspaces", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Travel Request Workspaces", description: "Request workspace metadata", href: "/platform/travel-request-workspaces", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Passenger Workspaces", description: "Passenger workspace metadata", href: "/platform/passenger-workspaces", icon: "user", badge: "Metadata only", metadata_only: true },
      { label: "Flight Workspaces", description: "Flight workspace metadata", href: "/platform/flight-workspaces", icon: "plane", badge: "Metadata only", metadata_only: true },
      { label: "Trip Workspaces", description: "Trip workspace metadata", href: "/platform/trip-workspaces", icon: "plane", badge: "Metadata only", metadata_only: true },
      { label: "Journey Engine", description: "Canonical journey and itinerary projection diagnostics", href: "/platform/journey-engine", icon: "git", badge: "Presentation layer", metadata_only: true },
      { label: "Journey Authoring", description: "Import, provenance, validation, and application diagnostics", href: "/platform/journey-authoring", icon: "clipboard", badge: "Read-only diagnostics", metadata_only: true },
      { label: "Journey Option Compositions", description: "Itinerary, fare-brand, pricing, comparison, and handoff diagnostics", href: "/platform/journey-option-compositions", icon: "rows", badge: "Read-only diagnostics", metadata_only: true },
      { label: "Journey Comparison Presentations", description: "Client-safe comparison, snapshot, review, and handoff diagnostics", href: "/platform/journey-comparison-presentations", icon: "rows", badge: "Read-only diagnostics", metadata_only: true },
      { label: "Offer Workspaces", description: "Offer workspace metadata", href: "/platform/offer-workspaces", icon: "rows", badge: "Metadata only", metadata_only: true },
      { label: "Booking Workspaces", description: "Booking workspace metadata", href: "/platform/booking-workspaces", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Ticket Workspaces", description: "Ticket workspace metadata", href: "/platform/ticket-workspaces", icon: "files", badge: "Metadata only", metadata_only: true },
      { label: "EMD Workspaces", description: "EMD workspace metadata", href: "/platform/emd-workspaces", icon: "files", badge: "Metadata only", metadata_only: true },
      { label: "SSR / OSI Operations", description: "Passenger service operation metadata", href: "/platform/ssr-osi-workspaces", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Document Workspaces", description: "Operational document workspace metadata", href: "/platform/document-workspaces", icon: "files", badge: "Metadata only", metadata_only: true },
      { label: "Operational Timelines", description: "Operational history metadata", href: "/platform/operational-timelines", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Operational Workflows", description: "Shared workflow-state and guarded transition metadata", href: "/platform/operational-workflows", icon: "git", badge: "Metadata only", metadata_only: true },
      { label: "Work Queue Governance", description: "Canonical work queue and assignment metadata", href: "/platform/work-queues", icon: "rows", badge: "Metadata only", metadata_only: true },
      { label: "SLA Policies", description: "Operational SLA policies, calendars, and deadline metadata", href: "/platform/sla-policies", icon: "check", badge: "Metadata only", metadata_only: true },
      { label: "Task Automation", description: "Safe task templates, dependencies, and automation run metadata", href: "/platform/task-automation", icon: "rows", badge: "Metadata only", metadata_only: true },
      { label: "Request-to-Trip Conversion", description: "Conversion run, mapping, and issue diagnostics", href: "/platform/request-trip-conversion", icon: "git", badge: "Read-only", metadata_only: true },
      { label: "Booking Handoffs", description: "Accepted-offer to booking readiness diagnostics", href: "/platform/booking-handoffs", icon: "git", badge: "Read-only", metadata_only: true },
      { label: "After-Sales Workflows", description: "Servicing, refund, exchange, claim, amendment, and disruption metadata", href: "/platform/after-sales", icon: "clipboard", badge: "Read-only", metadata_only: true },
      { label: "Operations Governance", description: "Read-only aggregate command center across agency operations", href: "/platform/operations-governance", icon: "rows", badge: "Read-only", metadata_only: true },
      { label: "Workflow Maturity", description: "Epic 54 end-to-end maturity assessment and isolated golden-path diagnostics", href: "/platform/workflow-maturity", icon: "check", badge: "Diagnostics", metadata_only: true },
      { label: "Passenger Service Workflows", description: "Workflow engine metadata", href: "/platform/passenger-service-workflows", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Subscriptions & Entitlements", description: "Plan and agency entitlement metadata", href: "/platform/saas-subscriptions", icon: "layers", badge: "No billing" },
      { label: "Feature Flags", description: "Agency feature visibility metadata", href: "/platform/feature-flags", icon: "layers", badge: "Metadata only" },
      { label: "Feature Flag Audit", description: "Read-only feature audit history", href: "/platform/feature-flag-audit", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Flag Bundles", description: "Reusable feature grouping metadata", href: "/platform/feature-flag-bundles", icon: "layers", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Assignments", description: "Agency bundle assignment metadata", href: "/platform/feature-bundle-assignments", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Dependencies", description: "Informational dependency metadata", href: "/platform/feature-bundle-dependencies", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Readiness", description: "Assignment readiness checklists", href: "/platform/feature-bundle-rollout-readiness", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Plans", description: "Planned rollout metadata", href: "/platform/feature-bundle-rollout-plans", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Approvals", description: "Rollout plan approval metadata", href: "/platform/feature-bundle-rollout-approvals", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Change Requests", description: "Change request register metadata", href: "/platform/feature-bundle-rollout-change-requests", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Decisions", description: "Decision register metadata", href: "/platform/feature-bundle-rollout-decisions", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Issues", description: "Rollout issue log metadata", href: "/platform/feature-bundle-rollout-issues", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Risks", description: "Rollout risk register metadata", href: "/platform/feature-bundle-rollout-risks", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Rollback Plans", description: "Rollback plan metadata", href: "/platform/feature-bundle-rollout-rollback-plans", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Summary Packs", description: "Summary evidence pack metadata", href: "/platform/feature-bundle-rollout-summary-packs", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Schedule", description: "Intended rollout timing metadata", href: "/platform/feature-bundle-rollout-schedule", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Feature Bundle Rollout Timeline", description: "Historical rollout event metadata", href: "/platform/feature-bundle-rollout-timeline", icon: "clipboard", badge: "Read-only", metadata_only: true },
      { label: "Rollout Dashboard", description: "Unified rollout metadata visibility", href: "/platform/rollout-dashboard", icon: "clipboard", badge: "Read-only", metadata_only: true },
      { label: "Capability Catalog", description: "Canonical capability inventory", href: "/platform/capabilities", icon: "database", badge: "Metadata only", metadata_only: true },
      { label: "Agencies", description: "Subscribed travel agency workspaces", href: "/platform/agencies", icon: "building", badge: "Platform only" },
      { label: "Reference Data", description: "Shared platform lookup data", href: "/platform/reference", icon: "database", badge: "Platform only" },
      { label: "Blueprint", description: "Route and model alignment", href: "/platform/blueprint", icon: "git", badge: "Read-only" },
    ],
  },
  {
    title: "Airline Intelligence Governance",
    description: "Platform owners curate airline data packs, policies, service taxonomy, mechanics, pricing, and safe agency visibility.",
    audience: "Platform only",
    safety: "No provider execution",
    items: [
      { label: "Airlines / Knowledge", description: "Global airline records", href: "/platform/airlines", icon: "plane", badge: "Platform only" },
      { label: "Airline Master Profiles", description: "Canonical airline identity enrichment and governance", href: "/platform/airline-master-profiles", icon: "plane", badge: "Platform only", metadata_only: true },
      { label: "Airline Evidence", description: "Source, assertion, conflict, freshness, and access governance", href: "/platform/airline-evidence", icon: "files", badge: "Platform only", metadata_only: true },
      { label: "Knowledge Versions", description: "Immutable snapshots, structured changes, impacts, and revalidation", href: "/platform/knowledge-versions", icon: "git", badge: "Platform only", metadata_only: true },
      { label: "Airline Service Coverage", description: "Coverage matrix, deterministic scores, gaps, and remediation", href: "/platform/airline-service-coverage", icon: "rows", badge: "Platform only", metadata_only: true },
      { label: "Distribution Capabilities", description: "Airline channel, PSS, GDS, NDC, fulfillment, and servicing intelligence", href: "/platform/airline-distribution-capabilities", icon: "rows", badge: "Planning only", metadata_only: true },
      { label: "Interline & Codeshare Intelligence", description: "Carrier relationships, responsibility rules, continuity, baggage, and EMD intelligence", href: "/platform/interline-codeshare-intelligence", icon: "git", badge: "Advisory only", metadata_only: true },
      { label: "Fare Brand Intelligence", description: "Fare families, RBD mappings, baggage rules, commercial attributes, and evidence", href: "/platform/fare-brand-intelligence", icon: "rows", badge: "Intelligence only", metadata_only: true },
      { label: "Airline Contact Intelligence", description: "Governed desks, channels, hours, templates, escalation paths, verification, and evidence", href: "/platform/airline-contact-intelligence", icon: "phone", badge: "No sending", metadata_only: true },
      { label: "Airline Intelligence Readiness", description: "Epic 55 readiness matrix, release gates, candidates, waves, and blockers", href: "/platform/airline-intelligence-readiness", icon: "check", badge: "Human release", metadata_only: true },
      { label: "Airline Operational Intelligence", description: "AOIE architecture map", href: "/platform/airline-operational-intelligence", icon: "layers", badge: "Architecture only", metadata_only: true },
      { label: "Airline Knowledge Acquisition", description: "Manual airline source evidence intake", href: "/platform/airline-knowledge-acquisition", icon: "file", badge: "Metadata only", metadata_only: true },
      { label: "Operational Constraints", description: "AOIE constraint language metadata", href: "/platform/operational-constraints", icon: "git", badge: "No live evaluation", metadata_only: true },
      { label: "Airline Knowledge Normalisation", description: "Canonical AOIE vocabulary metadata", href: "/platform/airline-knowledge-normalisation", icon: "tags", badge: "Metadata only", metadata_only: true },
      { label: "Knowledge Governance", description: "AOIE lifecycle and version metadata", href: "/platform/airline-knowledge-governance", icon: "git", badge: "Metadata only", metadata_only: true },
      { label: "Knowledge Releases", description: "Grouped airline knowledge releases", href: "/platform/airline-knowledge-releases", icon: "layers", badge: "No publication", metadata_only: true },
      { label: "Airline Capability Matrix", description: "Operational capability inventory", href: "/platform/airline-capability-matrix", icon: "rows", badge: "No evaluation", metadata_only: true },
      { label: "Operational Knowledge Evaluations", description: "Deterministic operational evaluation metadata", href: "/platform/operational-evaluations", icon: "check", badge: "No recommendation", metadata_only: true },
      { label: "Passenger Service Feasibility", description: "Advisory non-Boolean feasibility metadata", href: "/platform/passenger-service-feasibility", icon: "check", badge: "No ranking", metadata_only: true },
      { label: "Airline Recommendations", description: "Advisory airline and itinerary recommendation metadata", href: "/platform/airline-recommendations", icon: "check", badge: "No booking", metadata_only: true },
      { label: "Operational Intelligence Cases", description: "Chapter 50 pipeline case consolidation", href: "/platform/operational-intelligence-cases", icon: "rows", badge: "Metadata only", metadata_only: true },
      { label: "Reference Data Engine", description: "AOIE production reference domains", href: "/platform/reference-data-engine", icon: "database", badge: "Metadata only", metadata_only: true },
      { label: "Knowledge Import Templates", description: "Reusable knowledge population schemas", href: "/platform/knowledge-import-templates", icon: "file", badge: "Metadata only", metadata_only: true },
      { label: "Visual Policy Editor", description: "Structured airline service policy cards", href: "/platform/visual-policy-editor", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Pricing Formula Builder", description: "No-code pricing formula metadata", href: "/platform/pricing-formula-builder", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Operational Rule Composer", description: "No-code compound rule metadata", href: "/platform/operational-rule-composer", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Knowledge QA", description: "Airline knowledge QA reviews", href: "/platform/knowledge-quality-assurance", icon: "check", badge: "Metadata only", metadata_only: true },
      { label: "Knowledge Publishing", description: "Controlled airline knowledge publication metadata", href: "/platform/knowledge-publishing", icon: "layers", badge: "Metadata only", metadata_only: true },
      { label: "Scenario Testing", description: "Passenger service scenario test metadata", href: "/platform/operational-scenario-testing", icon: "clipboard", badge: "No live tests", metadata_only: true },
      { label: "Knowledge Population Toolkit", description: "Airline knowledge population readiness", href: "/platform/knowledge-population-toolkit", icon: "clipboard", badge: "Metadata only", metadata_only: true },
      { label: "Pilot Readiness", description: "End-to-end stabilization diagnostics", href: "/platform/pilot-readiness", icon: "check", badge: "Metadata only", metadata_only: true },
      { label: "Service Parameter Taxonomies", description: "Reusable measurable service parameters", href: "/platform/service-parameter-taxonomies", icon: "tags", badge: "Metadata only", metadata_only: true },
      { label: "Request Segment Services", description: "Segment-first intake service scope metadata", href: "/platform/request-segment-services", icon: "rows", badge: "Metadata only", metadata_only: true },
      { label: "Airline Data Packs", description: "Staged airline intelligence", href: "/platform/airline-intelligence-data-packs", icon: "file", badge: "Metadata only" },
      { label: "Data Pack Reviews", description: "Checklist and conflict review", href: "/platform/airline-intelligence-data-pack-reviews", icon: "git", badge: "Metadata only" },
      { label: "Knowledge Versions", description: "Release-channel metadata", href: "/platform/airline-intelligence-knowledge-versions", icon: "layers", badge: "Metadata only" },
      { label: "Agency Consumption", description: "Safe-use visibility bridge", href: "/platform/airline-intelligence-agency-consumption", icon: "layers", badge: "Metadata only" },
      { label: "Policy Ingestion", description: "Source and extraction review", href: "/platform/airline-policy-ingestion", icon: "file", badge: "Metadata only" },
      { label: "Service Taxonomy", description: "Canonical service meaning", href: "/platform/service-taxonomy", icon: "tags", badge: "Metadata only" },
      { label: "Service Mechanics", description: "SSR/EMD handling metadata", href: "/platform/service-mechanics", icon: "check", badge: "No execution" },
      { label: "Ancillary Pricing", description: "Non-binding price metadata", href: "/platform/ancillary-pricing", icon: "check", badge: "No payments" },
      { label: "Policy Comparison", description: "Comparison profile metadata", href: "/platform/policy-comparison", icon: "rows", badge: "No recommendations" },
    ],
  },
  {
    title: "Agency Website/CMS Governance",
    description: "Platform owners inspect shared website/CMS foundations while agencies maintain their own public site content.",
    audience: "Platform only",
    safety: "No publishing yet",
    items: [
      { label: "Documents", description: "Platform document templates", href: "/platform/document-templates", icon: "file", badge: "Metadata only" },
      { label: "GDS Parser", description: "Parser profiles and samples", href: "/platform/gds-parser", icon: "database", badge: "No provider calls" },
    ],
  },
  {
    title: "CRM / Client Portal Governance",
    description: "Platform owners can see the foundations agencies use for clients, passengers, portal visibility, and controlled actions.",
    audience: "Platform only",
    safety: "No automatic sending",
    items: [
      { label: "Client Master", description: "Commercial owner master metadata", href: "/platform/client-master", icon: "users", badge: "Metadata only", metadata_only: true },
      { label: "Passenger Master", description: "Operational identity master metadata", href: "/platform/passenger-master", icon: "user", badge: "Metadata only", metadata_only: true },
      { label: "Rules & Services", description: "Shared request service rules", href: "/platform/rules-services", icon: "check", badge: "Platform only" },
    ],
  },
  {
    title: "Offer & Document Governance",
    description: "Platform owners review offer advisor, decision evidence, export, release, delivery, audit, compliance, and document metadata.",
    audience: "Platform only",
    safety: "No booking or payment",
    items: [
      { label: "Intelligent Offer Builder", description: "Offer-intelligence package metadata", href: "/platform/intelligent-offer-builder", icon: "rows", badge: "No sending", metadata_only: true },
      { label: "Offer Advisor", description: "Offer policy diagnostics", href: "/platform/offer-policy-advisor", icon: "rows", badge: "Read-only" },
      { label: "Decision Packs", description: "Offer evidence bundles", href: "/platform/offer-decision-packs", icon: "rows", badge: "Read-only" },
      { label: "Decision Explanations", description: "Human explanation timelines", href: "/platform/offer-decision-explanations", icon: "rows", badge: "Read-only" },
      { label: "Decision Exports", description: "Review export metadata", href: "/platform/offer-decision-exports", icon: "file", badge: "No sending" },
      { label: "Export Previews", description: "Render preview metadata", href: "/platform/offer-decision-export-previews", icon: "file", badge: "No PDF delivery" },
      { label: "Export Releases", description: "Manual readiness metadata", href: "/platform/offer-decision-export-releases", icon: "file", badge: "Manual only" },
      { label: "Export Handoffs", description: "Manual handoff metadata", href: "/platform/offer-decision-export-deliveries", icon: "file", badge: "No sending" },
      { label: "Export Outcomes", description: "Human-recorded outcomes", href: "/platform/offer-decision-export-delivery-outcomes", icon: "file", badge: "Metadata only" },
      { label: "Export Audits", description: "Lifecycle review records", href: "/platform/offer-decision-export-audit-reviews", icon: "file", badge: "Read-only" },
      { label: "Export Governance", description: "Retention and legal metadata", href: "/platform/offer-decision-export-governance", icon: "file", badge: "Metadata only" },
      { label: "Export Compliance", description: "Evidence metadata", href: "/platform/offer-decision-export-compliance", icon: "file", badge: "Metadata only" },
    ],
  },
  {
    title: "System Readiness",
    description: "Platform owners verify health, phase readiness, safe boundaries, and canonical route policy before release.",
    audience: "Platform only",
    safety: "Read-only",
    items: [
      { label: "Readiness", description: "Health and phase state", href: "/platform", icon: "shield", badge: "Read-only" },
    ],
  },
]

export const agencyModuleGroups = [
  {
    title: "Daily Work",
    description: "Agency staff start here for new requests, intake review, and active work queues.",
    audience: "Agency workspace",
    safety: "Manual operations",
    items: [
      { label: "Dashboard", description: "Workspace home", href: "/agency", icon: "building", entitlementKey: "dashboard" },
      { label: "Create request", description: "Start a staff request", href: "/agency/requests/new", icon: "plus", entitlementKey: "requests" },
      { label: "Intakes", description: "Public and portal queue", href: "/agency/request-intakes", icon: "inbox", entitlementKey: "request_intakes" },
      { label: "Travel Workspaces", description: "Operational travel workspace metadata", href: "/agency/travel-workspaces", icon: "clipboard", badge: "Read-only", entitlementKey: "requests", metadata_only: true },
      { label: "Travel Requests", description: "Request workspace metadata", href: "/agency/travel-requests", icon: "clipboard", badge: "Read-only", entitlementKey: "requests", metadata_only: true },
      { label: "Passenger Workspaces", description: "Passenger workspace metadata", href: "/agency/passenger-workspaces", icon: "user", badge: "Read-only", entitlementKey: "requests", metadata_only: true },
      { label: "Flight Workspaces", description: "Flight workspace metadata", href: "/agency/flight-workspaces", icon: "plane", badge: "Read-only", entitlementKey: "requests", metadata_only: true },
      { label: "Trip Workspaces", description: "Trip workspace metadata", href: "/agency/trip-workspaces", icon: "plane", badge: "Read-only", entitlementKey: "requests", metadata_only: true },
      { label: "Journeys", description: "Canonical itinerary views and immutable presentation snapshots", href: "/agency/journeys", icon: "git", badge: "Projection layer", entitlementKey: "requests", metadata_only: true },
      { label: "Journey Authoring", description: "Paste, normalize, validate, and apply itinerary segment drafts", href: "/agency/journey-authoring", icon: "clipboard", badge: "Governed drafts", entitlementKey: "requests", metadata_only: true },
      { label: "Journey Option Composition", description: "Compose route alternatives, fare brands, prices, comparisons, and offer handoffs", href: "/agency/journey-option-composition", icon: "rows", badge: "Offer preparation", entitlementKey: "offers", metadata_only: true },
      { label: "Journey Comparison Presentations", description: "Review itinerary and fare-brand comparisons for client presentation", href: "/agency/journey-comparison-presentations", icon: "rows", badge: "Client review", entitlementKey: "offers", metadata_only: true },
      { label: "Offer Workspaces", description: "Offer workspace metadata", href: "/agency/offer-workspaces", icon: "rows", badge: "Read-only", entitlementKey: "offers", metadata_only: true },
      { label: "Booking Workspaces", description: "Booking workspace metadata", href: "/agency/booking-workspaces", icon: "clipboard", badge: "Read-only", entitlementKey: "booking_workspaces", metadata_only: true },
      { label: "Ticket Workspaces", description: "Ticket workspace metadata", href: "/agency/ticket-workspaces", icon: "files", badge: "Read-only", entitlementKey: "tickets_emds", metadata_only: true },
      { label: "EMD Workspaces", description: "EMD workspace metadata", href: "/agency/emd-workspaces", icon: "files", badge: "Read-only", entitlementKey: "tickets_emds", metadata_only: true },
      { label: "Passenger Services", description: "SSR / OSI service workspace metadata", href: "/agency/passenger-services", icon: "clipboard", badge: "Read-only", entitlementKey: "tickets_emds", metadata_only: true },
      { label: "Timeline", description: "Operational history metadata", href: "/agency/timeline", icon: "clipboard", badge: "Read-only", entitlementKey: "requests", metadata_only: true },
      { label: "Operational Workflows", description: "Workflow-state and guarded transition metadata", href: "/agency/operational-workflows", icon: "git", badge: "Metadata only", entitlementKey: "requests", metadata_only: true },
      { label: "Agent Work Queue", description: "Canonical operational work and assignment queue", href: "/agency/work-queue", icon: "rows", badge: "Metadata only", entitlementKey: "work_queue", metadata_only: true },
      { label: "Deadlines", description: "SLA and operational deadline metadata", href: "/agency/deadlines", icon: "check", badge: "Metadata only", entitlementKey: "deadlines", metadata_only: true },
      { label: "Task Automation", description: "Safe task templates, dependencies, and automation runs", href: "/agency/task-automation", icon: "rows", badge: "Metadata only", entitlementKey: "task_automation", metadata_only: true },
      { label: "Request-to-Trip Conversion", description: "Auditable request conversion wizard", href: "/agency/request-trip-conversion", icon: "git", badge: "Metadata only", entitlementKey: "requests", metadata_only: true },
      { label: "Booking Handoffs", description: "Accepted-offer booking readiness handoff", href: "/agency/booking-handoffs", icon: "git", badge: "Metadata only", entitlementKey: "booking_handoffs", metadata_only: true },
      { label: "After-Sales", description: "Servicing, refund, exchange, claim, amendment, and disruption case metadata", href: "/agency/after-sales", icon: "clipboard", badge: "Metadata only", entitlementKey: "after_sales", metadata_only: true },
      { label: "Operations Command Center", description: "Primary agency operational command center", href: "/agency/operations-command-center", icon: "rows", badge: "Read-only", entitlementKey: "operations_command_center", metadata_only: true },
      { label: "Workflow Maturity", description: "Operational maturity, blockers, coverage, and isolated diagnostics", href: "/agency/workflow-maturity", icon: "check", badge: "Diagnostics", entitlementKey: "workflow_maturity", metadata_only: true },
      { label: "Workflow Engine", description: "Passenger service workflow metadata", href: "/agency/workflow-engine", icon: "clipboard", badge: "Read-only", entitlementKey: "requests", metadata_only: true },
      { label: "GDS Parser", description: "Parse review only", href: "/agency/gds-parser", icon: "database", badge: "No provider calls", entitlementKey: "gds_parser" },
    ],
  },
  {
    title: "Clients & Passengers",
    description: "Agency-owned CRM records for requesters, travelers, relationships, and portal-facing profiles.",
    audience: "Agency workspace",
    safety: "Agency owned",
    items: [
      { label: "Clients", description: "Client master commercial-owner records", href: "/agency/clients", icon: "users", badge: "Metadata only", entitlementKey: "crm", metadata_only: true },
      { label: "Passengers", description: "Passenger master operational identity records", href: "/agency/passengers", icon: "user", badge: "Metadata only", entitlementKey: "crm", metadata_only: true },
      { label: "Portal Actions", description: "Controlled client actions", href: "/agency/portal-actions", icon: "globe", badge: "Manual only", entitlementKey: "client_portal" },
    ],
  },
  {
    title: "Requests, Offers & Trips",
    description: "Agency staff manage requests, trip dossiers, offer options, internal booking mirrors, tickets, EMDs, and service cases.",
    audience: "Agency workspace",
    safety: "No live provider execution",
    items: [
      { label: "Requests", description: "Operational work", href: "/agency/requests", icon: "clipboard", entitlementKey: "requests" },
      { label: "Trips", description: "Travel dossiers", href: "/agency/trips", icon: "plane", entitlementKey: "trips" },
      { label: "Offers", description: "Compare options", href: "/agency/offers", icon: "sparkles", entitlementKey: "offers" },
      { label: "Offer Intelligence", description: "Offer-intelligence packages", href: "/agency/offer-intelligence", icon: "rows", badge: "No sending", entitlementKey: "offers", metadata_only: true },
      { label: "Booking Handoffs", description: "Accepted-offer readiness handoff", href: "/agency/booking-handoffs", icon: "git", badge: "Metadata only", entitlementKey: "booking_handoffs", metadata_only: true },
      { label: "After-Sales", description: "Unified servicing cases", href: "/agency/after-sales", icon: "clipboard", badge: "Metadata only", entitlementKey: "after_sales", metadata_only: true },
      { label: "Operations Command Center", description: "Operational workload, exceptions, calendar, and team load", href: "/agency/operations-command-center", icon: "rows", badge: "Read-only", entitlementKey: "operations_command_center", metadata_only: true },
      { label: "Workflow Maturity", description: "Epic 54 maturity and golden-path diagnostics", href: "/agency/workflow-maturity", icon: "check", badge: "Diagnostics", entitlementKey: "workflow_maturity", metadata_only: true },
      { label: "Booking Mirrors", description: "Internal PNR mirror records", href: "/agency/booking-workspaces", icon: "clipboard", badge: "Read-only", entitlementKey: "booking_workspaces", metadata_only: true },
      { label: "Booking Imports", description: "GDS drafts", href: "/agency/booking-imports", icon: "files", badge: "Review only", entitlementKey: "booking_imports" },
      { label: "Tickets & EMDs", description: "Mirror records", href: "/agency/tickets-emds", icon: "files", badge: "No issuance", entitlementKey: "tickets_emds" },
      { label: "Refunds & Exchanges", description: "Service cases", href: "/agency/refunds-exchanges", icon: "clipboard", badge: "Manual only", entitlementKey: "refunds_exchanges" },
    ],
  },
  {
    title: "Website/CMS",
    description: "Agency staff maintain their own website content and media. Public publishing stays controlled by CMS safety settings.",
    audience: "Agency workspace",
    safety: "No publishing yet",
    items: [
      { label: "Website / CMS", description: "Public content drafts", href: "/agency/website", icon: "globe", badge: "No publishing yet", entitlementKey: "cms" },
      { label: "CMS Media", description: "Website assets", href: "/agency/website/media", icon: "files", badge: "Public-safe media", entitlementKey: "cms_media" },
    ],
  },
  {
    title: "Airline Intelligence Visibility",
    description: "Agency staff consume platform-reviewed airline intelligence as read-only guidance for daily work.",
    audience: "Agency read-only",
    safety: "Metadata only",
    items: [
      { label: "Airline Profiles", description: "Approved airline identity and operational summaries", href: "/agency/airline-profiles", icon: "plane", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Airline Evidence", description: "Approved evidence summaries and freshness", href: "/agency/airline-evidence", icon: "files", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Knowledge Updates", description: "Published airline knowledge changes and operational warnings", href: "/agency/knowledge-updates", icon: "git", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Airline Service Coverage", description: "Usable published coverage and missing-scope warnings", href: "/agency/airline-service-coverage", icon: "rows", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Distribution Capabilities", description: "Published channel availability, warnings, and booking fallbacks", href: "/agency/distribution-capabilities", icon: "rows", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Interline & Codeshare Advisor", description: "Published itinerary carrier roles and responsibility guidance", href: "/agency/interline-codeshare-advisor", icon: "git", badge: "Advisory", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Fare Brand Library", description: "Published fare-brand comparisons, baggage summaries, and operational caveats", href: "/agency/fare-brand-library", icon: "rows", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Airline Contact Directory", description: "Published desk finder, operating hours, communication checklists, and manual interaction history", href: "/agency/airline-contact-directory", icon: "phone", badge: "No sending", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Airline Intelligence Readiness", description: "Assigned released airline coverage, usable modules, freshness, and warnings", href: "/agency/airline-intelligence-readiness", icon: "check", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Operational Intelligence", description: "AOIE architecture map", href: "/agency/operational-intelligence", icon: "layers", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Knowledge Acquisition", description: "Airline source evidence metadata", href: "/agency/knowledge-acquisition", icon: "file", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Operational Constraints", description: "AOIE constraint language metadata", href: "/agency/operational-constraints", icon: "git", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Knowledge Normalisation", description: "Canonical AOIE vocabulary metadata", href: "/agency/knowledge-normalisation", icon: "tags", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Knowledge Governance", description: "Lifecycle and release metadata", href: "/agency/knowledge-governance", icon: "git", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Capability Matrix", description: "Airline operational capability inventory", href: "/agency/capability-matrix", icon: "rows", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Operational Evaluations", description: "Operational knowledge evaluation metadata", href: "/agency/operational-evaluations", icon: "check", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Service Feasibility", description: "Advisory service feasibility metadata", href: "/agency/service-feasibility", icon: "check", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Recommendations", description: "Airline and itinerary recommendation metadata", href: "/agency/recommendations", icon: "check", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Intelligence Cases", description: "Operational intelligence pipeline case view", href: "/agency/intelligence-cases", icon: "rows", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Reference Data", description: "AOIE production reference domains", href: "/agency/reference-data-engine", icon: "database", badge: "Read-only", entitlementKey: "reference_data_engine", metadata_only: true },
      { label: "Import Templates", description: "Reusable knowledge population schemas", href: "/agency/import-templates", icon: "file", badge: "Read-only", entitlementKey: "knowledge_import_templates", metadata_only: true },
      { label: "Policy Editor", description: "Structured airline service policy cards", href: "/agency/policy-editor", icon: "clipboard", badge: "Read-only", entitlementKey: "visual_policy_editor", metadata_only: true },
      { label: "Pricing Formula Builder", description: "No-code pricing formula metadata", href: "/agency/pricing-formula-builder", icon: "clipboard", badge: "Read-only", entitlementKey: "pricing_formula_builder", metadata_only: true },
      { label: "Rule Composer", description: "No-code compound rule metadata", href: "/agency/rule-composer", icon: "clipboard", badge: "Read-only", entitlementKey: "operational_rule_composer", metadata_only: true },
      { label: "Knowledge QA", description: "Airline knowledge QA reviews", href: "/agency/knowledge-quality-assurance", icon: "check", badge: "Read-only", entitlementKey: "knowledge_quality_assurance", metadata_only: true },
      { label: "Published Knowledge", description: "Agency-visible knowledge publication metadata", href: "/agency/published-knowledge", icon: "layers", badge: "Read-only", entitlementKey: "airline_knowledge_publishing", metadata_only: true },
      { label: "Scenario Testing", description: "Passenger service scenario examples", href: "/agency/scenario-testing", icon: "clipboard", badge: "Read-only", entitlementKey: "operational_scenario_testing", metadata_only: true },
      { label: "Knowledge Population Toolkit", description: "Airline knowledge population readiness", href: "/agency/knowledge-population-toolkit", icon: "clipboard", badge: "Read-only", entitlementKey: "knowledge_population_toolkit", metadata_only: true },
      { label: "Pilot Readiness", description: "End-to-end stabilization diagnostics", href: "/agency/pilot-readiness", icon: "check", badge: "Read-only", entitlementKey: "pilot_readiness", metadata_only: true },
      { label: "Service Parameter Taxonomies", description: "Reusable measurable service parameters", href: "/agency/service-parameter-taxonomies", icon: "tags", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Request Segment Services", description: "Segment-first intake service scope metadata", href: "/agency/request-segment-services", icon: "rows", badge: "Read-only", entitlementKey: "airline_intelligence", metadata_only: true },
      { label: "Policy Library", description: "Airline rules", href: "/agency/airline-policy-library", icon: "database", badge: "Agency read-only", entitlementKey: "airline_intelligence" },
      { label: "Airline Coverage", description: "Data readiness", href: "/agency/airline-intelligence-coverage", icon: "plane", badge: "Agency read-only", entitlementKey: "airline_coverage" },
      { label: "Review Coverage", description: "Safe-use status", href: "/agency/airline-intelligence-review-coverage", icon: "clipboard", badge: "Agency read-only", entitlementKey: "airline_coverage" },
      { label: "Knowledge Versions", description: "Visible airline data", href: "/agency/airline-intelligence-knowledge-versions", icon: "files", badge: "Agency read-only", entitlementKey: "knowledge_versions" },
      { label: "Airline Intelligence Usage", description: "Safe-use bridge", href: "/agency/airline-intelligence-consumption", icon: "files", badge: "Agency read-only", entitlementKey: "airline_intelligence_consumption" },
      { label: "Service Taxonomy", description: "Canonical services", href: "/agency/service-taxonomy", icon: "tags", badge: "Agency read-only", entitlementKey: "service_taxonomy" },
      { label: "Service Mechanics", description: "SSR/EMD lookup", href: "/agency/service-mechanics", icon: "clipboard", badge: "Metadata only", entitlementKey: "service_mechanics" },
      { label: "Ancillary Pricing", description: "Price estimates", href: "/agency/ancillary-pricing", icon: "clipboard", badge: "No payments", entitlementKey: "ancillary_pricing" },
      { label: "Policy Comparison", description: "Airline operations", href: "/agency/policy-comparison", icon: "rows", badge: "No recommendations", entitlementKey: "policy_comparison" },
      { label: "Service Advisor", description: "Operational guidance", href: "/agency/airline-service-advisor", icon: "clipboard", badge: "Human review", entitlementKey: "airline_service_advisor" },
      { label: "Offer Advisor", description: "Offer policy context", href: "/agency/offer-policy-advisor", icon: "rows", badge: "Metadata only", entitlementKey: "offer_policy_advisor" },
    ],
  },
  {
    title: "Documents & Delivery",
    description: "Agency staff review document packages, offer decision evidence, manual release readiness, handoffs, and outcomes.",
    audience: "Agency workspace",
    safety: "No automatic sending",
    items: [
      { label: "Document Workspaces", description: "Operational document metadata", href: "/agency/document-workspaces", icon: "files", badge: "Read-only", entitlementKey: "documents", metadata_only: true },
      { label: "Documents", description: "Rendered files", href: "/agency/documents", icon: "files", badge: "Manual only", entitlementKey: "documents" },
      { label: "Decision Packs", description: "Offer evidence", href: "/agency/offer-decision-packs", icon: "rows", badge: "Human review", entitlementKey: "offer_decision_evidence" },
      { label: "Decision Explanations", description: "Timeline audit", href: "/agency/offer-decision-explanations", icon: "rows", badge: "Metadata only", entitlementKey: "offer_decision_evidence" },
      { label: "Decision Exports", description: "Review snapshots", href: "/agency/offer-decision-exports", icon: "files", badge: "No sending", entitlementKey: "offer_exports" },
      { label: "Export Previews", description: "Render review", href: "/agency/offer-decision-export-previews", icon: "files", badge: "No PDF delivery", entitlementKey: "offer_exports" },
      { label: "Export Releases", description: "Manual readiness", href: "/agency/offer-decision-export-releases", icon: "files", badge: "Manual only", entitlementKey: "offer_exports" },
      { label: "Export Handoffs", description: "Manual metadata", href: "/agency/offer-decision-export-deliveries", icon: "files", badge: "No sending", entitlementKey: "manual_delivery" },
      { label: "Export Outcomes", description: "Manual tracking", href: "/agency/offer-decision-export-delivery-outcomes", icon: "files", badge: "Metadata only", entitlementKey: "manual_delivery" },
      { label: "Export Audits", description: "Read-only review trail", href: "/agency/offer-decision-export-audit-reviews", icon: "files", badge: "Agency read-only", entitlementKey: "offer_decision_evidence" },
      { label: "Export Policy", description: "Retention metadata", href: "/agency/offer-decision-export-governance", icon: "files", badge: "Metadata only", entitlementKey: "offer_decision_evidence" },
      { label: "Export Compliance Evidence", description: "Proof metadata", href: "/agency/offer-decision-export-compliance", icon: "files", badge: "Metadata only", entitlementKey: "offer_decision_evidence" },
    ],
  },
  {
    title: "Settings",
    description: "Agency staff configure team access, brand settings, forms, reference data suggestions, and workspace preferences.",
    audience: "Agency workspace",
    safety: "Agency owned",
    items: [
      { label: "Team", description: "Staff access", href: "/agency", icon: "users", badge: "Dashboard", entitlementKey: "dashboard" },
      { label: "My Subscription", description: "Assigned plan and entitlements", href: "/agency/saas-subscription", icon: "layers", badge: "Agency read-only", entitlementKey: "subscription" },
      { label: "Feature Availability", description: "Feature visibility metadata", href: "/agency/feature-availability", icon: "layers", badge: "Agency read-only", entitlementKey: "settings" },
      { label: "Feature Readiness", description: "Feature checklist metadata", href: "/agency/feature-readiness", icon: "clipboard", badge: "Metadata only", entitlementKey: "settings", metadata_only: true },
      { label: "Feature Bundles", description: "Available feature bundle metadata", href: "/agency/feature-bundles", icon: "layers", badge: "Metadata only", entitlementKey: "settings", metadata_only: true },
      { label: "Assigned Bundles", description: "Feature bundle assignment metadata", href: "/agency/assigned-bundles", icon: "clipboard", badge: "Metadata only", entitlementKey: "settings", metadata_only: true },
      { label: "Bundle Dependencies", description: "Read-only dependency metadata", href: "/agency/bundle-dependencies", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Bundle Rollout Readiness", description: "Read-only bundle readiness summaries", href: "/agency/bundle-rollout-readiness", icon: "clipboard", badge: "Metadata only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Plans", description: "Read-only bundle rollout plan metadata", href: "/agency/rollout-plans", icon: "clipboard", badge: "Metadata only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Approval", description: "Read-only rollout approval metadata", href: "/agency/rollout-approval", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Change Requests", description: "Read-only rollout change request metadata", href: "/agency/rollout-change-requests", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Decisions", description: "Read-only decision register metadata", href: "/agency/rollout-decisions", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Issues", description: "Read-only rollout issue metadata", href: "/agency/rollout-issues", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Risks", description: "Read-only rollout risk metadata", href: "/agency/rollout-risks", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Rollback Plans", description: "Read-only rollout rollback plan metadata", href: "/agency/rollout-rollback-plans", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Summary Packs", description: "Read-only rollout summary evidence metadata", href: "/agency/rollout-summary-packs", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Schedule", description: "Read-only rollout timing metadata", href: "/agency/rollout-schedule", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Timeline", description: "Read-only rollout event history", href: "/agency/rollout-timeline", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Rollout Dashboard", description: "Read-only rollout metadata dashboard", href: "/agency/rollout-dashboard", icon: "clipboard", badge: "Read-only", entitlementKey: "settings", metadata_only: true },
      { label: "Available Capabilities", description: "Capability catalog visibility metadata", href: "/agency/capabilities", icon: "database", badge: "Metadata only", entitlementKey: "settings", metadata_only: true },
      { label: "Reference Data", description: "Lookups and suggestions", href: "/agency/reference", icon: "database", badge: "Suggest only", entitlementKey: "reference_data" },
      { label: "Form Profiles", description: "Field menus", href: "/agency/settings/forms", icon: "clipboard", entitlementKey: "form_profiles" },
      { label: "Settings", description: "Brand and theme", href: "/agency/settings", icon: "settings", entitlementKey: "settings" },
    ],
  },
]

export function flattenModuleGroups(groups) {
  return groups.flatMap((group) => group.items.map((item) => ({ ...item, group: group.title })))
}

export const entitlementVisibilityLabels = {
  included: "Included",
  limited: "Limited",
  review_required: "Review required",
  not_included: "Not included",
  unknown: "Unknown",
}

export const entitlementVisibilityTone = {
  included: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  limited: "bg-amber-50 text-amber-700 ring-amber-200",
  review_required: "bg-sky-50 text-sky-700 ring-sky-200",
  not_included: "bg-slate-100 text-slate-600 ring-slate-200",
  unknown: "bg-zinc-50 text-zinc-600 ring-zinc-200",
}

export function entitlementVisibilityForItem(item, visibilityByKey = {}) {
  return visibilityByKey[item.entitlementKey] || visibilityByKey[item.href] || null
}

export function entitlementLabel(status) {
  return entitlementVisibilityLabels[status] || entitlementVisibilityLabels.unknown
}

export function entitlementTone(status) {
  return entitlementVisibilityTone[status] || entitlementVisibilityTone.unknown
}

export function summarizeEntitlementVisibility(items, visibilityByKey = {}) {
  return items.reduce((counts, item) => {
    const visibility = entitlementVisibilityForItem(item, visibilityByKey)
    const status = visibility?.status || "unknown"
    counts[status] = (counts[status] || 0) + 1
    return counts
  }, {})
}

export const featureFlagLabels = {
  enabled: "Enabled",
  disabled: "Disabled",
  hidden: "Hidden",
  beta: "Beta",
  pilot: "Pilot",
}

export const featureFlagTone = {
  enabled: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  disabled: "bg-slate-100 text-slate-600 ring-slate-200",
  hidden: "bg-zinc-50 text-zinc-600 ring-zinc-200",
  beta: "bg-sky-50 text-sky-700 ring-sky-200",
  pilot: "bg-violet-50 text-violet-700 ring-violet-200",
}

export function featureFlagLabel(state) {
  return featureFlagLabels[state] || featureFlagLabels.disabled
}

export function featureFlagClass(state) {
  return featureFlagTone[state] || featureFlagTone.disabled
}
